import { contentLocaleDefinition, type ContentLocale, type CopyLocale } from "../../content-locales";
import type { GuideRouteKey } from "./types";

export type ChromeCopy = {
  skip: string;
  navAria: string;
  console: string;
  guides: string;
  howItWorks: string;
  destinations: string;
  continueReading: string;
  home: string;
  language: string;
  popularDestinations: string;
  allDestinations: string;
  guideNavAria: string;
  introNavAria: string;
  related: Record<GuideRouteKey, string>;
  introLinks: Record<Exclude<GuideRouteKey, "home">, string>;
  regions: Record<string, string>;
  overview: string;
  flyingContext: string;
  seasonality: string;
  referencePoint: string;
  coordinates: (lat: string, lon: string) => string;
  openForecast: string;
  externalReference: string;
  relatedDestinations: string;
  destinationLink: (name: string) => string;
  guideLabels: Record<GuideRouteKey, string>;
};

const en: ChromeCopy = {
  skip: "Skip to main content",
  navAria: "Primary",
  console: "Flight console",
  guides: "Guides",
  howItWorks: "How it works",
  destinations: "Destinations",
  continueReading: "Continue reading",
  home: "Home",
  language: "Language",
  popularDestinations: "Popular paragliding destinations",
  allDestinations: "All destinations",
  guideNavAria: "Guides",
  introNavAria: "GlideWeather guides",
  related: {
    home: "Home",
    about: "About GlideWeather",
    howItWorks: "How GlideWeather works",
    paraglidingWeather: "Paragliding weather guide",
    whenToFly: "When to check conditions",
    flightWindow: "Flight window explained",
    faq: "FAQ",
    destinationsHub: "Destinations",
  },
  introLinks: {
    about: "Learn what GlideWeather is and who it serves",
    howItWorks: "See how location data becomes a flight window",
    paraglidingWeather: "Understand paragliding wind and instability signals",
    whenToFly: "Know when to check conditions before travelling",
    flightWindow: "Learn how GlideWeather evaluates a flight window",
    faq: "Read paragliding weather FAQ",
    destinationsHub: "Explore popular paragliding destinations",
  },
  regions: {
    europe: "Europe",
    asia: "Asia",
    africa: "Africa",
    oceania: "Oceania",
    northAmerica: "North America",
    southAmerica: "South America",
    romania: "Romania",
  },
  overview: "Overview",
  flyingContext: "Flying context",
  seasonality: "Seasonality",
  referencePoint: "Forecast reference point",
  coordinates: (lat, lon) =>
    `Coordinates: ${lat}°, ${lon}°. The forecast is computed for this grid point, not every launch in the area.`,
  openForecast: "Open forecast in console",
  externalReference: "External reference: ",
  relatedDestinations: "Related destinations",
  destinationLink: (name) => `${name} paragliding weather`,
  guideLabels: {
    home: "Home",
    about: "About GlideWeather",
    howItWorks: "How it works",
    paraglidingWeather: "Paragliding weather",
    whenToFly: "When to fly",
    flightWindow: "Flight window",
    faq: "FAQ",
    destinationsHub: "Destinations",
  },
};

const ro: ChromeCopy = {
  ...en,
  skip: "Sari la conținutul principal",
  navAria: "Navigare principală",
  console: "Consolă zbor",
  guides: "Ghiduri",
  howItWorks: "Cum funcționează",
  destinations: "Destinații",
  continueReading: "Continuă lectura",
  home: "Acasă",
  language: "Limbă",
  popularDestinations: "Destinații populare parapantă",
  allDestinations: "Toate destinațiile",
  guideNavAria: "Ghiduri",
  introNavAria: "Ghiduri GlideWeather",
  related: {
    home: "Acasă",
    about: "Despre GlideWeather",
    howItWorks: "Cum funcționează GlideWeather",
    paraglidingWeather: "Ghid meteo parapantă",
    whenToFly: "Când să verifici condițiile",
    flightWindow: "Fereastra de zbor explicată",
    faq: "Întrebări frecvente",
    destinationsHub: "Destinații",
  },
  introLinks: {
    about: "Află ce este GlideWeather și pentru cine este",
    howItWorks: "Vezi cum locația devine fereastră de zbor",
    paraglidingWeather: "Înțelege semnalele de vânt și instabilitate",
    whenToFly: "Când să verifici condițiile înainte de drum",
    flightWindow: "Cum evaluează GlideWeather fereastra de zbor",
    faq: "Întrebări frecvente meteo parapantă",
    destinationsHub: "Explorează destinații populare de parapantă",
  },
  regions: { ...en.regions, europe: "Europa", northAmerica: "America de Nord", southAmerica: "America de Sud", romania: "România" },
  overview: "Prezentare",
  flyingContext: "Context de zbor",
  seasonality: "Sezonalitate",
  referencePoint: "Punct de referință prognoză",
  coordinates: (lat, lon) =>
    `Coordonate: ${lat}°, ${lon}°. Prognoza se calculează pentru acest punct de grilă, nu pentru fiecare decolare din zonă.`,
  openForecast: "Deschide prognoza în consolă",
  externalReference: "Referință externă: ",
  relatedDestinations: "Alte destinații",
  destinationLink: (name) => `Meteo parapantă ${name}`,
  guideLabels: {
    home: "Acasă",
    about: "Despre GlideWeather",
    howItWorks: "Cum funcționează",
    paraglidingWeather: "Meteo parapantă",
    whenToFly: "Când să zbori",
    flightWindow: "Fereastra de zbor",
    faq: "Întrebări frecvente",
    destinationsHub: "Destinații",
  },
};

function fromEnglish(patch: Partial<ChromeCopy> & Pick<ChromeCopy, "skip" | "navAria" | "console" | "guides" | "howItWorks" | "destinations" | "continueReading" | "home" | "language" | "popularDestinations" | "allDestinations" | "guideNavAria" | "introNavAria" | "related" | "introLinks" | "overview" | "flyingContext" | "seasonality" | "referencePoint" | "coordinates" | "openForecast" | "externalReference" | "relatedDestinations" | "destinationLink" | "guideLabels">): ChromeCopy {
  return { ...en, regions: patch.regions ?? en.regions, ...patch };
}

const de = fromEnglish({
  skip: "Zum Inhalt springen",
  navAria: "Hauptnavigation",
  console: "Flugkonsole",
  guides: "Ratgeber",
  howItWorks: "So funktioniert es",
  destinations: "Fluggebiete",
  continueReading: "Weiterlesen",
  home: "Start",
  language: "Sprache",
  popularDestinations: "Beliebte Gleitschirmgebiete",
  allDestinations: "Alle Gebiete",
  guideNavAria: "Ratgeber",
  introNavAria: "GlideWeather-Ratgeber",
  related: {
    home: "Start",
    about: "Über GlideWeather",
    howItWorks: "So funktioniert GlideWeather",
    paraglidingWeather: "Gleitschirmwetter",
    whenToFly: "Wann prüfen",
    flightWindow: "Flugfenster erklärt",
    faq: "FAQ",
    destinationsHub: "Fluggebiete",
  },
  introLinks: {
    about: "Was GlideWeather ist und für wen",
    howItWorks: "Wie aus dem Ort ein Flugfenster wird",
    paraglidingWeather: "Wind- und Labilitätssignale verstehen",
    whenToFly: "Wann du die Bedingungen vor der Fahrt prüfst",
    flightWindow: "Wie GlideWeather ein Flugfenster bewertet",
    faq: "FAQ zum Gleitschirmwetter",
    destinationsHub: "Beliebte Gleitschirmgebiete ansehen",
  },
  regions: { ...en.regions, europe: "Europa", northAmerica: "Nordamerika", southAmerica: "Südamerika", romania: "Rumänien" },
  overview: "Überblick",
  flyingContext: "Flugkontext",
  seasonality: "Saison",
  referencePoint: "Referenzpunkt der Prognose",
  coordinates: (lat, lon) =>
    `Koordinaten: ${lat}°, ${lon}°. Die Prognose gilt für diesen Gitterpunkt, nicht für jeden Start im Gebiet.`,
  openForecast: "Prognose in der Konsole öffnen",
  externalReference: "Externe Referenz: ",
  relatedDestinations: "Weitere Gebiete",
  destinationLink: (name) => `Gleitschirmwetter ${name}`,
  guideLabels: {
    home: "Start",
    about: "Über GlideWeather",
    howItWorks: "So funktioniert es",
    paraglidingWeather: "Gleitschirmwetter",
    whenToFly: "Wann fliegen",
    flightWindow: "Flugfenster",
    faq: "FAQ",
    destinationsHub: "Fluggebiete",
  },
});

const itChrome = fromEnglish({
  skip: "Vai al contenuto",
  navAria: "Navigazione principale",
  console: "Console di volo",
  guides: "Guide",
  howItWorks: "Come funziona",
  destinations: "Destinazioni",
  continueReading: "Continua a leggere",
  home: "Home",
  language: "Lingua",
  popularDestinations: "Destinazioni popolari di parapendio",
  allDestinations: "Tutte le destinazioni",
  guideNavAria: "Guide",
  introNavAria: "Guide GlideWeather",
  related: {
    home: "Home",
    about: "Informazioni su GlideWeather",
    howItWorks: "Come funziona GlideWeather",
    paraglidingWeather: "Meteo parapendio",
    whenToFly: "Quando controllare",
    flightWindow: "Finestra di volo",
    faq: "Domande frequenti",
    destinationsHub: "Destinazioni",
  },
  introLinks: {
    about: "Scopri cos’è GlideWeather e a chi serve",
    howItWorks: "Come il luogo diventa una finestra di volo",
    paraglidingWeather: "Capire vento e instabilità",
    whenToFly: "Quando controllare prima di partire",
    flightWindow: "Come GlideWeather valuta la finestra di volo",
    faq: "Domande frequenti sul meteo",
    destinationsHub: "Esplora le destinazioni popolari",
  },
  regions: { ...en.regions, europe: "Europa", northAmerica: "America del Nord", southAmerica: "America del Sud", romania: "Romania" },
  overview: "Panoramica",
  flyingContext: "Contesto di volo",
  seasonality: "Stagione",
  referencePoint: "Punto di riferimento della previsione",
  coordinates: (lat, lon) =>
    `Coordinate: ${lat}°, ${lon}°. La previsione vale per questo punto di griglia, non per ogni decollo dell’area.`,
  openForecast: "Apri la previsione nella console",
  externalReference: "Riferimento esterno: ",
  relatedDestinations: "Altre destinazioni",
  destinationLink: (name) => `Meteo parapendio ${name}`,
  guideLabels: {
    home: "Home",
    about: "Informazioni",
    howItWorks: "Come funziona",
    paraglidingWeather: "Meteo parapendio",
    whenToFly: "Quando volare",
    flightWindow: "Finestra di volo",
    faq: "Domande frequenti",
    destinationsHub: "Destinazioni",
  },
});

const es = fromEnglish({
  skip: "Saltar al contenido",
  navAria: "Navegación principal",
  console: "Consola de vuelo",
  guides: "Guías",
  howItWorks: "Cómo funciona",
  destinations: "Destinos",
  continueReading: "Seguir leyendo",
  home: "Inicio",
  language: "Idioma",
  popularDestinations: "Destinos populares de parapente",
  allDestinations: "Todos los destinos",
  guideNavAria: "Guías",
  introNavAria: "Guías de GlideWeather",
  related: {
    home: "Inicio",
    about: "Acerca de GlideWeather",
    howItWorks: "Cómo funciona GlideWeather",
    paraglidingWeather: "Meteo parapente",
    whenToFly: "Cuándo consultar",
    flightWindow: "Ventana de vuelo",
    faq: "Preguntas frecuentes",
    destinationsHub: "Destinos",
  },
  introLinks: {
    about: "Qué es GlideWeather y para quién es",
    howItWorks: "Cómo el lugar se convierte en ventana de vuelo",
    paraglidingWeather: "Entender viento e inestabilidad",
    whenToFly: "Cuándo mirar el meteo antes de salir",
    flightWindow: "Cómo GlideWeather evalúa la ventana",
    faq: "Preguntas frecuentes de meteo",
    destinationsHub: "Ver destinos populares",
  },
  regions: { ...en.regions, europe: "Europa", northAmerica: "América del Norte", southAmerica: "América del Sur", romania: "Rumanía" },
  overview: "Resumen",
  flyingContext: "Contexto de vuelo",
  seasonality: "Temporada",
  referencePoint: "Punto de referencia del pronóstico",
  coordinates: (lat, lon) =>
    `Coordenadas: ${lat}°, ${lon}°. El pronóstico es para este punto de rejilla, no para cada despegue de la zona.`,
  openForecast: "Abrir el pronóstico en la consola",
  externalReference: "Referencia externa: ",
  relatedDestinations: "Otros destinos",
  destinationLink: (name) => `Meteo parapente ${name}`,
  guideLabels: {
    home: "Inicio",
    about: "Acerca de",
    howItWorks: "Cómo funciona",
    paraglidingWeather: "Meteo parapente",
    whenToFly: "Cuándo volar",
    flightWindow: "Ventana de vuelo",
    faq: "Preguntas frecuentes",
    destinationsHub: "Destinos",
  },
});

const pt = fromEnglish({
  skip: "Saltar para o conteúdo",
  navAria: "Navegação principal",
  console: "Consola de voo",
  guides: "Guias",
  howItWorks: "Como funciona",
  destinations: "Destinos",
  continueReading: "Continuar a ler",
  home: "Início",
  language: "Idioma",
  popularDestinations: "Destinos populares de parapente",
  allDestinations: "Todos os destinos",
  guideNavAria: "Guias",
  introNavAria: "Guias GlideWeather",
  related: {
    home: "Início",
    about: "Sobre o GlideWeather",
    howItWorks: "Como funciona o GlideWeather",
    paraglidingWeather: "Meteo parapente",
    whenToFly: "Quando consultar",
    flightWindow: "Janela de voo",
    faq: "Perguntas frequentes",
    destinationsHub: "Destinos",
  },
  introLinks: {
    about: "O que é o GlideWeather e para quem serve",
    howItWorks: "Como o local se torna uma janela de voo",
    paraglidingWeather: "Perceber vento e instabilidade",
    whenToFly: "Quando ver o meteo antes de partir",
    flightWindow: "Como o GlideWeather avalia a janela",
    faq: "Perguntas frequentes de meteo",
    destinationsHub: "Ver destinos populares",
  },
  regions: { ...en.regions, europe: "Europa", northAmerica: "América do Norte", southAmerica: "América do Sul", romania: "Roménia" },
  overview: "Visão geral",
  flyingContext: "Contexto de voo",
  seasonality: "Época",
  referencePoint: "Ponto de referência da previsão",
  coordinates: (lat, lon) =>
    `Coordenadas: ${lat}°, ${lon}°. A previsão vale para este ponto de grelha, não para cada descolagem da zona.`,
  openForecast: "Abrir a previsão na consola",
  externalReference: "Referência externa: ",
  relatedDestinations: "Outros destinos",
  destinationLink: (name) => `Meteo parapente ${name}`,
  guideLabels: {
    home: "Início",
    about: "Sobre",
    howItWorks: "Como funciona",
    paraglidingWeather: "Meteo parapente",
    whenToFly: "Quando voar",
    flightWindow: "Janela de voo",
    faq: "Perguntas frequentes",
    destinationsHub: "Destinos",
  },
});

const cs = fromEnglish({
  skip: "Přeskočit na obsah",
  navAria: "Hlavní navigace",
  console: "Letová konzole",
  guides: "Průvodci",
  howItWorks: "Jak to funguje",
  destinations: "Lokality",
  continueReading: "Číst dál",
  home: "Domů",
  language: "Jazyk",
  popularDestinations: "Oblíbené paraglidingové lokality",
  allDestinations: "Všechny lokality",
  guideNavAria: "Průvodci",
  introNavAria: "Průvodci GlideWeather",
  related: {
    home: "Domů",
    about: "O GlideWeather",
    howItWorks: "Jak GlideWeather funguje",
    paraglidingWeather: "Počasí pro paragliding",
    whenToFly: "Kdy kontrolovat",
    flightWindow: "Letové okno",
    faq: "Časté otázky",
    destinationsHub: "Lokality",
  },
  introLinks: {
    about: "Co je GlideWeather a pro koho je",
    howItWorks: "Jak se z místa stane letové okno",
    paraglidingWeather: "Vítr a nestabilita",
    whenToFly: "Kdy koukat na počasí před cestou",
    flightWindow: "Jak GlideWeather hodnotí okno",
    faq: "Časté otázky k počasí",
    destinationsHub: "Oblíbené lokality",
  },
  regions: { ...en.regions, europe: "Evropa", northAmerica: "Severní Amerika", southAmerica: "Jižní Amerika", romania: "Rumunsko" },
  overview: "Přehled",
  flyingContext: "Letový kontext",
  seasonality: "Sezóna",
  referencePoint: "Referenční bod předpovědi",
  coordinates: (lat, lon) =>
    `Souřadnice: ${lat}°, ${lon}°. Předpověď platí pro tento bod mřížky, ne pro každý start v oblasti.`,
  openForecast: "Otevřít předpověď v konzoli",
  externalReference: "Externí odkaz: ",
  relatedDestinations: "Další lokality",
  destinationLink: (name) => `Počasí pro paragliding ${name}`,
  guideLabels: {
    home: "Domů",
    about: "O nás",
    howItWorks: "Jak to funguje",
    paraglidingWeather: "Počasí pro paragliding",
    whenToFly: "Kdy letět",
    flightWindow: "Letové okno",
    faq: "Časté otázky",
    destinationsHub: "Lokality",
  },
});

const skChrome = fromEnglish({
  skip: "Preskočiť na obsah",
  navAria: "Hlavná navigácia",
  console: "Letová konzola",
  guides: "Sprievodcovia",
  howItWorks: "Ako to funguje",
  destinations: "Lokality",
  continueReading: "Čítať ďalej",
  home: "Domov",
  language: "Jazyk",
  popularDestinations: "Obľúbené paraglidingové lokality",
  allDestinations: "Všetky lokality",
  guideNavAria: "Sprievodcovia",
  introNavAria: "Sprievodcovia GlideWeather",
  related: {
    home: "Domov",
    about: "O GlideWeather",
    howItWorks: "Ako GlideWeather funguje",
    paraglidingWeather: "Počasie pre paragliding",
    whenToFly: "Kedy kontrolovať",
    flightWindow: "Letové okno",
    faq: "Časté otázky",
    destinationsHub: "Lokality",
  },
  introLinks: {
    about: "Čo je GlideWeather a pre koho je",
    howItWorks: "Ako sa z miesta stane letové okno",
    paraglidingWeather: "Vietor a nestabilita",
    whenToFly: "Kedy pozerať počasie pred cestou",
    flightWindow: "Ako GlideWeather hodnotí okno",
    faq: "Časté otázky k počasiu",
    destinationsHub: "Obľúbené lokality",
  },
  regions: { ...en.regions, europe: "Európa", northAmerica: "Severná Amerika", southAmerica: "Južná Amerika", romania: "Rumunsko" },
  overview: "Prehľad",
  flyingContext: "Letový kontext",
  seasonality: "Sezóna",
  referencePoint: "Referenčný bod predpovede",
  coordinates: (lat, lon) =>
    `Súradnice: ${lat}°, ${lon}°. Predpoveď platí pre tento bod mriežky, nie pre každý štart v oblasti.`,
  openForecast: "Otvoriť predpoveď v konzole",
  externalReference: "Externý odkaz: ",
  relatedDestinations: "Ďalšie lokality",
  destinationLink: (name) => `Počasie pre paragliding ${name}`,
  guideLabels: {
    home: "Domov",
    about: "O nás",
    howItWorks: "Ako to funguje",
    paraglidingWeather: "Počasie pre paragliding",
    whenToFly: "Kedy lietať",
    flightWindow: "Letové okno",
    faq: "Časté otázky",
    destinationsHub: "Lokality",
  },
});

const sl = fromEnglish({
  skip: "Preskoči na vsebino",
  navAria: "Glavna navigacija",
  console: "Letalna konzola",
  guides: "Vodniki",
  howItWorks: "Kako deluje",
  destinations: "Destinacije",
  continueReading: "Beri naprej",
  home: "Domov",
  language: "Jezik",
  popularDestinations: "Priljubljene destinacije",
  allDestinations: "Vse destinacije",
  guideNavAria: "Vodniki",
  introNavAria: "Vodniki GlideWeather",
  related: {
    home: "Domov",
    about: "O GlideWeather",
    howItWorks: "Kako deluje GlideWeather",
    paraglidingWeather: "Vreme za jadralno padalstvo",
    whenToFly: "Kdaj preveriti",
    flightWindow: "Letalno okno",
    faq: "Pogosta vprašanja",
    destinationsHub: "Destinacije",
  },
  introLinks: {
    about: "Kaj je GlideWeather in za koga je",
    howItWorks: "Kako lokacija postane letalno okno",
    paraglidingWeather: "Veter in nestabilnost",
    whenToFly: "Kdaj preveriti vreme pred potjo",
    flightWindow: "Kako GlideWeather oceni okno",
    faq: "Pogosta vprašanja o vremenu",
    destinationsHub: "Priljubljene destinacije",
  },
  regions: { ...en.regions, europe: "Evropa", northAmerica: "Severna Amerika", southAmerica: "Južna Amerika", romania: "Romunija" },
  overview: "Pregled",
  flyingContext: "Kontekst letenja",
  seasonality: "Sezona",
  referencePoint: "Referenčna točka napovedi",
  coordinates: (lat, lon) =>
    `Koordinate: ${lat}°, ${lon}°. Napoved velja za to točko mreže, ne za vsako vzletišče v območju.`,
  openForecast: "Odpri napoved v konzoli",
  externalReference: "Zunanja referenca: ",
  relatedDestinations: "Druge destinacije",
  destinationLink: (name) => `Vreme za jadralno padalstvo ${name}`,
  guideLabels: {
    home: "Domov",
    about: "O nas",
    howItWorks: "Kako deluje",
    paraglidingWeather: "Vreme za jadralno padalstvo",
    whenToFly: "Kdaj leteti",
    flightWindow: "Letalno okno",
    faq: "Pogosta vprašanja",
    destinationsHub: "Destinacije",
  },
});

const nl = fromEnglish({
  skip: "Naar de inhoud",
  navAria: "Hoofdnavigatie",
  console: "Vliegconsole",
  guides: "Gidsen",
  howItWorks: "Hoe het werkt",
  destinations: "Bestemmingen",
  continueReading: "Verder lezen",
  home: "Home",
  language: "Taal",
  popularDestinations: "Populaire paraglidingbestemmingen",
  allDestinations: "Alle bestemmingen",
  guideNavAria: "Gidsen",
  introNavAria: "GlideWeather-gidsen",
  related: {
    home: "Home",
    about: "Over GlideWeather",
    howItWorks: "Hoe GlideWeather werkt",
    paraglidingWeather: "Paraglidingweer",
    whenToFly: "Wanneer checken",
    flightWindow: "Vluchtvenster",
    faq: "Veelgestelde vragen",
    destinationsHub: "Bestemmingen",
  },
  introLinks: {
    about: "Wat GlideWeather is en voor wie",
    howItWorks: "Hoe een plek een vluchtvenster wordt",
    paraglidingWeather: "Wind en instabiliteit begrijpen",
    whenToFly: "Wanneer je het weer checkt vóór je rijdt",
    flightWindow: "Hoe GlideWeather een venster beoordeelt",
    faq: "Veelgestelde vragen over het weer",
    destinationsHub: "Populaire bestemmingen bekijken",
  },
  regions: { ...en.regions, europe: "Europa", northAmerica: "Noord-Amerika", southAmerica: "Zuid-Amerika", romania: "Roemenië" },
  overview: "Overzicht",
  flyingContext: "Vliegcontext",
  seasonality: "Seizoen",
  referencePoint: "Referentiepunt van de verwachting",
  coordinates: (lat, lon) =>
    `Coördinaten: ${lat}°, ${lon}°. De verwachting geldt voor dit rasterpunt, niet voor elke start in het gebied.`,
  openForecast: "Verwachting in de console openen",
  externalReference: "Externe referentie: ",
  relatedDestinations: "Andere bestemmingen",
  destinationLink: (name) => `Paraglidingweer ${name}`,
  guideLabels: {
    home: "Home",
    about: "Over",
    howItWorks: "Hoe het werkt",
    paraglidingWeather: "Paraglidingweer",
    whenToFly: "Wanneer vliegen",
    flightWindow: "Vluchtvenster",
    faq: "Veelgestelde vragen",
    destinationsHub: "Bestemmingen",
  },
});

const mtChrome = fromEnglish({
  skip: "Aqbeż għall-kontenut",
  navAria: "Navigazzjoni ewlenija",
  console: "Konsola tat-titjira",
  guides: "Gwidi",
  howItWorks: "Kif jaħdem",
  destinations: "Destinazzjonijiet",
  continueReading: "Kompli aqra",
  home: "Dar",
  language: "Lingwa",
  popularDestinations: "Destinazzjonijiet popolari tal-paragliding",
  allDestinations: "Id-destinazzjonijiet kollha",
  guideNavAria: "Gwidi",
  introNavAria: "Gwidi GlideWeather",
  related: {
    home: "Dar",
    about: "Dwar GlideWeather",
    howItWorks: "Kif jaħdem GlideWeather",
    paraglidingWeather: "Temp għall-paragliding",
    whenToFly: "Meta tiċċekkja",
    flightWindow: "Tieqa tat-titjira",
    faq: "Mistoqsijiet",
    destinationsHub: "Destinazzjonijiet",
  },
  introLinks: {
    about: "X’inhu GlideWeather u għal min hu",
    howItWorks: "Kif il-post isir tieqa tat-titjira",
    paraglidingWeather: "Ir-riħ u l-instabbiltà",
    whenToFly: "Meta tara t-temp qabel titlaq",
    flightWindow: "Kif GlideWeather jevalwa t-tieqa",
    faq: "Mistoqsijiet dwar it-temp",
    destinationsHub: "Destinazzjonijiet popolari",
  },
  regions: { ...en.regions, europe: "Ewropa", northAmerica: "Amerika ta’ Fuq", southAmerica: "Amerika t’Isfel", romania: "Rumanija" },
  overview: "Ħarsa ġenerali",
  flyingContext: "Kuntest tat-titjira",
  seasonality: "Staġun",
  referencePoint: "Punt ta’ referenza tat-tbassir",
  coordinates: (lat, lon) =>
    `Koordinati: ${lat}°, ${lon}°. It-tbassir huwa għal dan il-punt tal-grilja, mhux għal kull tlugħ fiż-żona.`,
  openForecast: "Iftaħ it-tbassir fil-konsola",
  externalReference: "Referenza esterna: ",
  relatedDestinations: "Destinazzjonijiet oħra",
  destinationLink: (name) => `Temp għall-paragliding ${name}`,
  guideLabels: {
    home: "Dar",
    about: "Dwar",
    howItWorks: "Kif jaħdem",
    paraglidingWeather: "Temp għall-paragliding",
    whenToFly: "Meta ttir",
    flightWindow: "Tieqa tat-titjira",
    faq: "Mistoqsijiet",
    destinationsHub: "Destinazzjonijiet",
  },
});

const tr = fromEnglish({
  skip: "İçeriğe geç",
  navAria: "Ana menü",
  console: "Uçuş konsolu",
  guides: "Rehberler",
  howItWorks: "Nasıl çalışır",
  destinations: "Bölgeler",
  continueReading: "Okumaya devam et",
  home: "Ana sayfa",
  language: "Dil",
  popularDestinations: "Popüler yamaç paraşütü bölgeleri",
  allDestinations: "Tüm bölgeler",
  guideNavAria: "Rehberler",
  introNavAria: "GlideWeather rehberleri",
  related: {
    home: "Ana sayfa",
    about: "GlideWeather hakkında",
    howItWorks: "GlideWeather nasıl çalışır",
    paraglidingWeather: "Yamaç paraşütü havası",
    whenToFly: "Ne zaman bakılır",
    flightWindow: "Uçuş penceresi",
    faq: "Sık sorulan sorular",
    destinationsHub: "Bölgeler",
  },
  introLinks: {
    about: "GlideWeather nedir, kim içindir",
    howItWorks: "Konum nasıl uçuş penceresine dönüşür",
    paraglidingWeather: "Rüzgar ve kararsızlık",
    whenToFly: "Yola çıkmadan havaya ne zaman bakılır",
    flightWindow: "GlideWeather pencereyi nasıl değerlendirir",
    faq: "Hava durumu SSS",
    destinationsHub: "Popüler bölgeleri gör",
  },
  regions: { ...en.regions, europe: "Avrupa", northAmerica: "Kuzey Amerika", southAmerica: "Güney Amerika", romania: "Romanya" },
  overview: "Genel bakış",
  flyingContext: "Uçuş bağlamı",
  seasonality: "Sezon",
  referencePoint: "Tahmin referans noktası",
  coordinates: (lat, lon) =>
    `Koordinatlar: ${lat}°, ${lon}°. Tahmin bu ızgara noktası içindir, bölgedeki her kalkış için değil.`,
  openForecast: "Tahmini konsolda aç",
  externalReference: "Dış referans: ",
  relatedDestinations: "Diğer bölgeler",
  destinationLink: (name) => `${name} yamaç paraşütü havası`,
  guideLabels: {
    home: "Ana sayfa",
    about: "Hakkında",
    howItWorks: "Nasıl çalışır",
    paraglidingWeather: "Yamaç paraşütü havası",
    whenToFly: "Ne zaman uçulur",
    flightWindow: "Uçuş penceresi",
    faq: "SSS",
    destinationsHub: "Bölgeler",
  },
});

const hrChrome = fromEnglish({
  skip: "Preskoči na sadržaj",
  navAria: "Glavna navigacija",
  console: "Letna konzola",
  guides: "Vodiči",
  howItWorks: "Kako radi",
  destinations: "Odredišta",
  continueReading: "Nastavi čitati",
  home: "Početna",
  language: "Jezik",
  popularDestinations: "Popularna odredišta za parajedrilicu",
  allDestinations: "Sva odredišta",
  guideNavAria: "Vodiči",
  introNavAria: "Vodiči GlideWeather",
  related: {
    home: "Početna",
    about: "O GlideWeatheru",
    howItWorks: "Kako radi GlideWeather",
    paraglidingWeather: "Vrijeme za parajedrilicu",
    whenToFly: "Kad provjeriti",
    flightWindow: "Prozor letenja",
    faq: "Česta pitanja",
    destinationsHub: "Odredišta",
  },
  introLinks: {
    about: "Što je GlideWeather i za koga je",
    howItWorks: "Kako lokacija postaje prozor letenja",
    paraglidingWeather: "Vjetar i nestabilnost",
    whenToFly: "Kad provjeriti vrijeme prije puta",
    flightWindow: "Kako GlideWeather ocjenjuje prozor",
    faq: "Česta pitanja o vremenu",
    destinationsHub: "Popularna odredišta",
  },
  regions: { ...en.regions, europe: "Europa", northAmerica: "Sjeverna Amerika", southAmerica: "Južna Amerika", romania: "Rumunjska" },
  overview: "Pregled",
  flyingContext: "Kontekst leta",
  seasonality: "Sezona",
  referencePoint: "Referentna točka prognoze",
  coordinates: (lat, lon) =>
    `Koordinate: ${lat}°, ${lon}°. Prognoza vrijedi za ovu točku mreže, ne za svako uzletište u području.`,
  openForecast: "Otvori prognozu u konzoli",
  externalReference: "Vanjska referenca: ",
  relatedDestinations: "Druga odredišta",
  destinationLink: (name) => `Vrijeme za parajedrilicu ${name}`,
  guideLabels: {
    home: "Početna",
    about: "O nama",
    howItWorks: "Kako radi",
    paraglidingWeather: "Vrijeme za parajedrilicu",
    whenToFly: "Kad letjeti",
    flightWindow: "Prozor letenja",
    faq: "Česta pitanja",
    destinationsHub: "Odredišta",
  },
});

const sr = fromEnglish({
  skip: "Preskoči na sadržaj",
  navAria: "Glavna navigacija",
  console: "Letna konzola",
  guides: "Vodiči",
  howItWorks: "Kako radi",
  destinations: "Destinacije",
  continueReading: "Nastavi čitanje",
  home: "Početna",
  language: "Jezik",
  popularDestinations: "Popularne destinacije za paraglajding",
  allDestinations: "Sve destinacije",
  guideNavAria: "Vodiči",
  introNavAria: "Vodiči GlideWeather",
  related: {
    home: "Početna",
    about: "O GlideWeather-u",
    howItWorks: "Kako radi GlideWeather",
    paraglidingWeather: "Vreme za paraglajding",
    whenToFly: "Kada proveriti",
    flightWindow: "Prozor letenja",
    faq: "Česta pitanja",
    destinationsHub: "Destinacije",
  },
  introLinks: {
    about: "Šta je GlideWeather i za koga je",
    howItWorks: "Kako lokacija postaje prozor letenja",
    paraglidingWeather: "Vetar i nestabilnost",
    whenToFly: "Kada proveriti vreme pre puta",
    flightWindow: "Kako GlideWeather ocenjuje prozor",
    faq: "Česta pitanja o vremenu",
    destinationsHub: "Popularne destinacije",
  },
  regions: { ...en.regions, europe: "Evropa", northAmerica: "Severna Amerika", southAmerica: "Južna Amerika", romania: "Rumunija" },
  overview: "Pregled",
  flyingContext: "Kontekst leta",
  seasonality: "Sezona",
  referencePoint: "Referentna tačka prognoze",
  coordinates: (lat, lon) =>
    `Koordinate: ${lat}°, ${lon}°. Prognoza važi za ovu tačku mreže, ne za svako uzletište u području.`,
  openForecast: "Otvori prognozu u konzoli",
  externalReference: "Spoljna referenca: ",
  relatedDestinations: "Druge destinacije",
  destinationLink: (name) => `Vreme za paraglajding ${name}`,
  guideLabels: {
    home: "Početna",
    about: "O nama",
    howItWorks: "Kako radi",
    paraglidingWeather: "Vreme za paraglajding",
    whenToFly: "Kada leteti",
    flightWindow: "Prozor letenja",
    faq: "Česta pitanja",
    destinationsHub: "Destinacije",
  },
});

const sq = fromEnglish({
  skip: "Kalo te përmbajtja",
  navAria: "Lundrimi kryesor",
  console: "Konsola e fluturimit",
  guides: "Udhëzues",
  howItWorks: "Si funksionon",
  destinations: "Destinacione",
  continueReading: "Vazhdo leximin",
  home: "Kreu",
  language: "Gjuha",
  popularDestinations: "Destinacione të njohura paragliding",
  allDestinations: "Të gjitha destinacionet",
  guideNavAria: "Udhëzues",
  introNavAria: "Udhëzues GlideWeather",
  related: {
    home: "Kreu",
    about: "Rreth GlideWeather",
    howItWorks: "Si funksionon GlideWeather",
    paraglidingWeather: "Moti për paragliding",
    whenToFly: "Kur të kontrollosh",
    flightWindow: "Dritarja e fluturimit",
    faq: "Pyetje të shpeshta",
    destinationsHub: "Destinacione",
  },
  introLinks: {
    about: "Çfarë është GlideWeather dhe për kë është",
    howItWorks: "Si vendi bëhet dritare fluturimi",
    paraglidingWeather: "Era dhe paqëndrueshmëria",
    whenToFly: "Kur të shohësh motin para rrugës",
    flightWindow: "Si e vlerëson GlideWeather dritaren",
    faq: "Pyetje të shpeshta për motin",
    destinationsHub: "Destinacione të njohura",
  },
  regions: { ...en.regions, europe: "Evropa", northAmerica: "Amerika e Veriut", southAmerica: "Amerika e Jugut", romania: "Rumania" },
  overview: "Përmbledhje",
  flyingContext: "Konteksti i fluturimit",
  seasonality: "Sezoni",
  referencePoint: "Pika e referencës së parashikimit",
  coordinates: (lat, lon) =>
    `Koordinata: ${lat}°, ${lon}°. Parashikimi vlen për këtë pikë rrjete, jo për çdo nisje në zonë.`,
  openForecast: "Hap parashikimin në konsolë",
  externalReference: "Referencë e jashtme: ",
  relatedDestinations: "Destinacione të tjera",
  destinationLink: (name) => `Moti për paragliding ${name}`,
  guideLabels: {
    home: "Kreu",
    about: "Rreth",
    howItWorks: "Si funksionon",
    paraglidingWeather: "Moti për paragliding",
    whenToFly: "Kur të fluturosh",
    flightWindow: "Dritarja e fluturimit",
    faq: "Pyetje të shpeshta",
    destinationsHub: "Destinacione",
  },
});

const chromeByCopy: Record<CopyLocale, ChromeCopy> = {
  en,
  ro,
  de,
  it: itChrome,
  es,
  pt,
  cs,
  sk: skChrome,
  sl,
  nl,
  mt: mtChrome,
  tr,
  hr: hrChrome,
  sr,
  sq,
};

export function chromeFor(locale: ContentLocale): ChromeCopy {
  return chromeByCopy[contentLocaleDefinition(locale).copy];
}
