import type { CopyLocale } from "../../content-locales";
import type { DestinationRecord, LocalizedText } from "./destinations";

type Blurb = {
  name: string;
  area: string;
  short: string;
  overview: string;
  flying: string;
  season: string;
};

const text = (en: string, copy?: CopyLocale, local?: string): LocalizedText =>
  copy && local ? { en, [copy]: local } : { en };

function site(
  id: string,
  countryCode: string,
  latitude: number,
  longitude: number,
  en: Blurb,
  local?: { copy: CopyLocale } & Blurb,
): DestinationRecord {
  return {
    id,
    slug: id,
    region: "europe",
    countryCode,
    latitude,
    longitude,
    names: text(en.name, local?.copy, local?.name),
    areas: text(en.area, local?.copy, local?.area),
    shortDescriptions: text(en.short, local?.copy, local?.short),
    overviews: text(en.overview, local?.copy, local?.overview),
    flyingContext: text(en.flying, local?.copy, local?.flying),
    seasonality: text(en.season, local?.copy, local?.season),
  };
}

const de = (blurb: Blurb) => ({ copy: "de" as const, ...blurb });
const it = (blurb: Blurb) => ({ copy: "it" as const, ...blurb });
const es = (blurb: Blurb) => ({ copy: "es" as const, ...blurb });
const pt = (blurb: Blurb) => ({ copy: "pt" as const, ...blurb });
const cs = (blurb: Blurb) => ({ copy: "cs" as const, ...blurb });
const sk = (blurb: Blurb) => ({ copy: "sk" as const, ...blurb });
const sl = (blurb: Blurb) => ({ copy: "sl" as const, ...blurb });
const nl = (blurb: Blurb) => ({ copy: "nl" as const, ...blurb });
const mt = (blurb: Blurb) => ({ copy: "mt" as const, ...blurb });
const tr = (blurb: Blurb) => ({ copy: "tr" as const, ...blurb });
const hr = (blurb: Blurb) => ({ copy: "hr" as const, ...blurb });
const sr = (blurb: Blurb) => ({ copy: "sr" as const, ...blurb });
const sq = (blurb: Blurb) => ({ copy: "sq" as const, ...blurb });

export const COUNTRY_DESTINATIONS: DestinationRecord[] = [
  site("long-mynd", "GB", 52.53, -2.863, {
    name: "Long Mynd",
    area: "Shropshire, England",
    short: "Mid-Wales border ridge used for soaring and cross-country.",
    overview: "Long Mynd is a broad Shropshire ridge with established hill soaring when the wind is on the west face.",
    flying: "Wind direction on the face matters more than the headline speed. GlideWeather scores 10 m wind and gust spread at this reference point.",
    season: "Flyable in many seasons; winter days are short and often wet.",
  }),
  site("combe-gibbet", "GB", 51.348, -1.482, {
    name: "Combe Gibbet",
    area: "Berkshire, England",
    short: "South-facing chalk ridge above the Kennet valley.",
    overview: "Combe Gibbet is a well-known southern England ridge for soaring when the wind is south or south-west.",
    flying: "Ridge lift dies quickly if the wind goes off the hill. Treat the score as a briefing, then check the actual face.",
    season: "Spring through autumn sees the most activity.",
  }),
  site("bradwell-edge", "GB", 53.326, -1.734, {
    name: "Bradwell Edge",
    area: "Peak District, England",
    short: "Gritstone edge used for west and south-west soaring.",
    overview: "Bradwell Edge is a Peak District soaring site with a defined face and busy club use when the wind is on the hill.",
    flying: "Gust spread and a wind that is too far off the edge are the usual reasons to wait. Confirm site rules before walking up.",
    season: "Year-round in suitable wind; daylight is short in winter.",
  }),
  site("ivinghoe-beacon", "GB", 51.838, -0.606, {
    name: "Ivinghoe Beacon",
    area: "Chilterns, England",
    short: "Chiltern ridge used for light-wind soaring.",
    overview: "Ivinghoe Beacon is a Chilterns ridge where light to moderate wind on the face can give soaring close to the hill.",
    flying: "Too little wind and a large gust spread both fail GlideWeather’s conservative filters. Local rotor behind the crest is not modelled.",
    season: "Most flights are spring to autumn.",
  }),
  site("southerndown", "GB", 51.452, -3.612, {
    name: "Southerndown",
    area: "Vale of Glamorgan, Wales",
    short: "Coastal cliff soaring on the Bristol Channel.",
    overview: "Southerndown is a Welsh coastal cliff used when the wind is on the face and the tide and cliff rules allow.",
    flying: "Sea breeze and cliff compression are local effects. The forecast reference is a grid point, not a substitute for the cliff briefing.",
    season: "Sea-breeze days are most common in warmer months.",
  }),
  site("frocester", "GB", 51.724, -2.308, {
    name: "Frocester",
    area: "Cotswolds, England",
    short: "Cotswold west-facing ridge.",
    overview: "Frocester is a Cotswold ridge used for soaring in west and south-west winds.",
    flying: "A wind that looks flyable in the model can be off the face or gusty in the valley. Read the reasons, then the hill.",
    season: "Spring to autumn is typical.",
  }),
  site("wasserkuppe", "DE", 50.4986, 9.9376, {
    name: "Wasserkuppe",
    area: "Rhön, Hesse",
    short: "The historic Rhön summit and a major German free-flight area.",
    overview: "Wasserkuppe is Germany’s best-known free-flight mountain, with several launches around the summit plateau.",
    flying: "Wind on the chosen face, gusts, and afternoon convection decide the day. GlideWeather does not map which launch is in.",
    season: "The long season runs from spring into autumn; winter is often snowbound.",
  }, de({
    name: "Wasserkuppe",
    area: "Rhön, Hessen",
    short: "Der historische Rhöngipfel und eines der wichtigsten deutschen Fluggebiete.",
    overview: "Die Wasserkuppe ist Deutschlands bekanntester Freiflugberg, mit mehreren Startplätzen um das Gipfelplateau.",
    flying: "Wind auf der gewählten Seite, Böen und Konvektion am Nachmittag entscheiden den Tag. GlideWeather zeigt nicht, welcher Start frei ist.",
    season: "Die Hauptsaison läuft vom Frühjahr bis in den Herbst; im Winter liegt oft Schnee.",
  })),
  site("hornisgrinde", "DE", 48.6058, 8.2014, {
    name: "Hornisgrinde",
    area: "Black Forest, Baden-Württemberg",
    short: "High Black Forest ridge with west-side soaring.",
    overview: "Hornisgrinde is a high Black Forest ridge used when the wind is on the west slopes.",
    flying: "Forest rotor and a wind that is too strong aloft are common reasons to wait. Confirm the local slot before launching.",
    season: "Late spring through early autumn.",
  }, de({
    name: "Hornisgrinde",
    area: "Schwarzwald, Baden-Württemberg",
    short: "Hoher Schwarzwaldkamm mit Westwind-Soaren.",
    overview: "Die Hornisgrinde ist ein hoher Kamm im Schwarzwald, genutzt wenn der Wind auf die Westhänge steht.",
    flying: "Waldrotor und zu starker Höhenwind sind häufige Gründe zu warten. Den lokalen Slot vor dem Start prüfen.",
    season: "Spätes Frühjahr bis früher Herbst.",
  })),
  site("tegelberg", "DE", 47.557, 10.783, {
    name: "Tegelberg",
    area: "Allgäu, Bavaria",
    short: "Alpine launch above Füssen and the royal castles.",
    overview: "Tegelberg is an Allgäu alpine launch with valley flying toward the Lech when conditions and airspace allow.",
    flying: "Alpine gusts and a valley wind that strengthens in the afternoon are the usual watch items.",
    season: "May to October, snow-limited outside that window.",
  }, de({
    name: "Tegelberg",
    area: "Allgäu, Bayern",
    short: "Alpiner Start über Füssen.",
    overview: "Der Tegelberg ist ein Allgäuer Bergstart mit Talfahrt Richtung Lech, wenn Wetter und Luftraum passen.",
    flying: "Alpine Böen und ein Talwind, der nachmittags zunimmt, sind die üblichen Punkte.",
    season: "Mai bis Oktober, außerhalb oft schneebedingt eingeschränkt.",
  })),
  site("papststein", "DE", 50.897, 14.14, {
    name: "Papststein",
    area: "Saxon Switzerland, Saxony",
    short: "Sandstone launch near Königstein.",
    overview: "Papststein is a Saxon Switzerland launch used for soaring and short cross-country when the wind is on the face.",
    flying: "Sandstone edges punish an off-face wind. The score uses 10 m wind at the reference point, not the cliff detail.",
    season: "Spring to autumn.",
  }, de({
    name: "Papststein",
    area: "Sächsische Schweiz, Sachsen",
    short: "Sandsteinstart bei Königstein.",
    overview: "Der Papststein ist ein Start in der Sächsischen Schweiz zum Soaren und für kurze Strecken, wenn der Wind auf der Wand steht.",
    flying: "Sandsteinkanten verzeihen keinen abgedrehten Wind. Der Score nutzt 10-m-Wind am Referenzpunkt, nicht das Kantenrelief.",
    season: "Frühjahr bis Herbst.",
  })),
  site("kreuzberg-rhoen", "DE", 50.37, 9.98, {
    name: "Kreuzberg",
    area: "Rhön, Bavaria",
    short: "Rhön monastery hill used alongside Wasserkuppe.",
    overview: "Kreuzberg is a Rhön summit near Wasserkuppe, flown when the wind suits its faces rather than the higher plateau.",
    flying: "Choosing Kreuzberg instead of Wasserkuppe is a local call. Compare both reference points in the console.",
    season: "Same broad season as the rest of the Rhön.",
  }, de({
    name: "Kreuzberg",
    area: "Rhön, Bayern",
    short: "Rhönberg neben der Wasserkuppe.",
    overview: "Der Kreuzberg ist ein Rhöngipfel nahe der Wasserkuppe und wird geflogen, wenn der Wind zu seinen Hängen passt.",
    flying: "Kreuzberg statt Wasserkuppe ist eine lokale Entscheidung. Beide Referenzpunkte in der Konsole vergleichen.",
    season: "Dieselbe breite Saison wie die übrige Rhön.",
  })),
  site("brauneck", "DE", 47.661, 11.528, {
    name: "Brauneck",
    area: "Bavarian Alps, Germany",
    short: "Alpine launch above Lenggries.",
    overview: "Brauneck is a Bavarian alpine launch above Lenggries, used for thermal flying into the Isar valley when the airmass is stable enough.",
    flying: "CAPE and gust spread are the model signals for a building alpine day. They are not a cloud-base measurement.",
    season: "Late spring through early autumn.",
  }, de({
    name: "Brauneck",
    area: "Bayerische Alpen",
    short: "Alpiner Start über Lenggries.",
    overview: "Das Brauneck ist ein bayerischer Bergstart über Lenggries für Thermikflug ins Isartal, wenn die Luftmasse ruhig genug ist.",
    flying: "CAPE und Böenspreizung sind die Modellsignale für einen aufbauenden Alpentag. Sie sind keine Wolkenbasis-Messung.",
    season: "Spätes Frühjahr bis früher Herbst.",
  })),
  site("emberger-alm", "AT", 46.766, 13.158, {
    name: "Emberger Alm",
    area: "Greifenburg, Carinthia",
    short: "Austria’s best-known cross-country launch above the Drau valley.",
    overview: "Emberger Alm above Greifenburg is a classic Austrian cross-country launch when valley wind and thermals line up.",
    flying: "A strong valley wind and high CAPE are the usual reasons the score drops in the afternoon.",
    season: "May to September is the core season.",
  }, de({
    name: "Emberger Alm",
    area: "Greifenburg, Kärnten",
    short: "Österreichs bekanntester Streckenstart über dem Drautal.",
    overview: "Die Emberger Alm über Greifenburg ist ein klassischer österreichischer Streckenstart, wenn Talwind und Thermik zusammenpassen.",
    flying: "Starker Talwind und hohes CAPE sind die üblichen Gründe, warum der Score am Nachmittag fällt.",
    season: "Mai bis September ist die Kernsaison.",
  })),
  site("gerlitzen", "AT", 46.692, 13.917, {
    name: "Gerlitzen",
    area: "Lake Ossiach, Carinthia",
    short: "Carinthian summit with views over several lakes.",
    overview: "Gerlitzen is a Carinthian mountain launch above Lake Ossiach, used for local and cross-country flights.",
    flying: "Lake breezes and summit wind can disagree. The reference point is the summit grid, not the lake shore.",
    season: "Late spring to early autumn.",
  }, de({
    name: "Gerlitzen",
    area: "Ossiacher See, Kärnten",
    short: "Kärntner Gipfel über mehreren Seen.",
    overview: "Die Gerlitzen ist ein Kärntner Bergstart über dem Ossiacher See für lokale und Streckenflüge.",
    flying: "Seewind und Gipfelwind können auseinanderlaufen. Der Referenzpunkt ist das Gipfelgitter, nicht das Ufer.",
    season: "Spätes Frühjahr bis früher Herbst.",
  })),
  site("hafelekar", "AT", 47.312, 11.383, {
    name: "Hafelekar",
    area: "Nordkette, Innsbruck",
    short: "Nordkette launch above Innsbruck.",
    overview: "Hafelekar on the Nordkette is the well-known launch above Innsbruck, with a steep alpine departure.",
    flying: "Inn valley wind and north föhn are local decisions. GlideWeather only scores the model at this coordinate.",
    season: "Snow-free months, mainly May to October.",
  }, de({
    name: "Hafelekar",
    area: "Nordkette, Innsbruck",
    short: "Start an der Nordkette über Innsbruck.",
    overview: "Das Hafelekar an der Nordkette ist der bekannte Start über Innsbruck, mit steilem alpinem Abflug.",
    flying: "Inntalwind und Nordföhn sind lokale Entscheidungen. GlideWeather bewertet nur das Modell an dieser Koordinate.",
    season: "Schneefreie Monate, vor allem Mai bis Oktober.",
  })),
  site("grubigstein", "AT", 47.403, 10.881, {
    name: "Grubigstein",
    area: "Lermoos, Tyrol",
    short: "Tyrolean launch above Lermoos and the Zugspitze side.",
    overview: "Grubigstein above Lermoos is a Tyrolean launch used for alpine thermal flying toward the Zugspitze massif.",
    flying: "Gusts increase when thermals fire on the rocky faces. A rising gust spread is a reason to read the hourly list again.",
    season: "June to September is typical.",
  }, de({
    name: "Grubigstein",
    area: "Lermoos, Tirol",
    short: "Tiroler Start über Lermoos.",
    overview: "Der Grubigstein über Lermoos ist ein Tiroler Start für alpinen Thermikflug Richtung Zugspitzmassiv.",
    flying: "Böen nehmen zu, wenn die Felsen thermisch werden. Eine wachsende Böenspreizung ist ein Grund, die Stundenliste erneut zu lesen.",
    season: "Juni bis September ist typisch.",
  })),
  site("schmittenhoehe", "AT", 47.328, 12.737, {
    name: "Schmittenhöhe",
    area: "Zell am See, Salzburg",
    short: "Summit launch above Zell am See.",
    overview: "Schmittenhöhe is the summit above Zell am See, flown for local soaring and hops into the Pinzgau.",
    flying: "Lake Zell can feed a breeze that the summit model only partly shows. Confirm on the terrace before clipping in.",
    season: "Late spring through early autumn.",
  }, de({
    name: "Schmittenhöhe",
    area: "Zell am See, Salzburg",
    short: "Gipfelstart über Zell am See.",
    overview: "Die Schmittenhöhe ist der Gipfel über Zell am See, für lokales Soaren und Sprünge ins Pinzgau.",
    flying: "Der Zeller See kann eine Brise schicken, die das Gipfelmodell nur teilweise zeigt. Auf der Terrasse prüfen, bevor eingeklinkt wird.",
    season: "Spätes Frühjahr bis früher Herbst.",
  })),
  site("unterberghorn", "AT", 47.64, 12.433, {
    name: "Unterberghorn",
    area: "Kössen, Tyrol",
    short: "North-Tyrol launch near the German border.",
    overview: "Unterberghorn near Kössen is a north-Tyrol launch used when the wind suits the Kaisergebirge side.",
    flying: "Border airspace and a wind turning along the Kaiser are local limits the score does not encode.",
    season: "May to September.",
  }, de({
    name: "Unterberghorn",
    area: "Kössen, Tirol",
    short: "Nordtiroler Start nahe der deutschen Grenze.",
    overview: "Das Unterberghorn bei Kössen ist ein Nordtiroler Start, wenn der Wind zur Kaisergebirgsseite passt.",
    flying: "Grenz-Luftraum und ein Wind, der am Kaiser entlangdreht, sind lokale Grenzen, die der Score nicht kennt.",
    season: "Mai bis September.",
  })),
  site("monte-cucco", "IT", 43.368, 12.748, {
    name: "Monte Cucco",
    area: "Umbria, Italy",
    short: "Appennine launch between Umbria and Marche.",
    overview: "Monte Cucco is a central Apennine launch used for soaring and cross-country over the Umbrian ridges.",
    flying: "Apennine wind can be light in the morning and gusty once cumulus builds. Read CAPE with the gust line.",
    season: "Spring and autumn are often the steadiest; summer afternoons can overdevelop.",
  }, it({
    name: "Monte Cucco",
    area: "Umbria, Italia",
    short: "Decollo appenninico tra Umbria e Marche.",
    overview: "Monte Cucco è un decollo dell’Appennino centrale per veleggiamento e cross sulle dorsali umbre.",
    flying: "Il vento appenninico può essere debole al mattino e rafficoso quando cresce il cumulo. Leggi il CAPE insieme alle raffiche.",
    season: "Primavera e autunno sono spesso i più stabili; i pomeriggi estivi possono sovrasviluppare.",
  })),
  site("meduno", "IT", 46.218, 12.798, {
    name: "Meduno",
    area: "Friuli, Italy",
    short: "Friulian pre-alpine launch.",
    overview: "Meduno is a Friuli launch on the pre-Alps, used for local flights and attempts toward the plain when the airmass is dry.",
    flying: "A southerly that looks moderate at 10 m can be turbulent on the relief. The reasons list is the briefing, not the clearance.",
    season: "April to October.",
  }, it({
    name: "Meduno",
    area: "Friuli, Italia",
    short: "Decollo prealpino in Friuli.",
    overview: "Meduno è un decollo friulano sulle Prealpi, per voli locali e tentativi verso la pianura quando la massa d’aria è secca.",
    flying: "Un sud che a 10 m sembra moderato può essere turbolento sul rilievo. L’elenco dei motivi è il briefing, non il via.",
    season: "Da aprile a ottobre.",
  })),
  site("monte-avena", "IT", 46.028, 11.832, {
    name: "Monte Avena",
    area: "Feltre, Veneto",
    short: "Dolomite foothill launch above Feltre.",
    overview: "Monte Avena is a Veneto launch on the southern Dolomite edge, used when the plain wind and the hill agree.",
    flying: "Afternoon plain wind can shut the cycle. Watch the hourly wind trend, not only the current sample.",
    season: "Late spring through early autumn.",
  }, it({
    name: "Monte Avena",
    area: "Feltre, Veneto",
    short: "Decollo pedemontano sopra Feltre.",
    overview: "Monte Avena è un decollo veneto sul bordo sud delle Dolomiti, quando il vento di pianura e il rilievo coincidono.",
    flying: "Il vento di pianura pomeridiano può chiudere il ciclo. Guarda la tendenza oraria, non solo il campione attuale.",
    season: "Dalla tarda primavera all’inizio dell’autunno.",
  })),
  site("monte-bondone", "IT", 45.988, 11.045, {
    name: "Monte Bondone",
    area: "Trento, Italy",
    short: "Summit plateau above Trento.",
    overview: "Monte Bondone is the high plateau above Trento, with launches that work in different wind directions around the massif.",
    flying: "Which side is working is a local choice. Pick the reference closest to the face you intend to use.",
    season: "Snow limits the season; summer and early autumn are the busiest.",
  }, it({
    name: "Monte Bondone",
    area: "Trento, Italia",
    short: "Altopiano sopra Trento.",
    overview: "Il Monte Bondone è l’altopiano sopra Trento, con decolli che funzionano con venti diversi intorno al massiccio.",
    flying: "Quale versante lavora è una scelta locale. Usa il riferimento più vicino al fronte che intendi usare.",
    season: "La neve limita la stagione; estate e inizio autunno sono i più frequentati.",
  })),
  site("monte-carpegna", "IT", 43.805, 12.318, {
    name: "Monte Carpegna",
    area: "Montefeltro, Italy",
    short: "Adriatic-side Apennine launch.",
    overview: "Monte Carpegna is a Montefeltro launch used for soaring above the Marecchia valley.",
    flying: "Sea influence can raise humidity and lower the estimated cloud base. That estimate is not a measured base.",
    season: "Spring and autumn are favoured; summer can be hazy.",
  }, it({
    name: "Monte Carpegna",
    area: "Montefeltro, Italia",
    short: "Decollo appenninico lato Adriatico.",
    overview: "Monte Carpegna è un decollo del Montefeltro per veleggiare sopra la valle del Marecchia.",
    flying: "L’influenza del mare può alzare l’umidità e abbassare la base stimata. Quella stima non è una base misurata.",
    season: "Primavera e autunno sono i periodi migliori; l’estate può essere fosca.",
  })),
  site("algodonales", "ES", 36.881, -5.406, {
    name: "Algodonales",
    area: "Cádiz, Andalusia",
    short: "Southern Spain thermal site in the Sierra de Líjar.",
    overview: "Algodonales is a well-known Andalusian thermal site, flown for local distance when the levante or poniente is not too strong.",
    flying: "Strong easterly or westerly flow overrides the thermal day. Gust spread is the model clue; the street is decided in the air.",
    season: "Autumn through spring is the main season; midsummer is often too hot and windy.",
  }, es({
    name: "Algodonales",
    area: "Cádiz, Andalucía",
    short: "Zona térmica del sur de España en la Sierra de Líjar.",
    overview: "Algodonales es una zona térmica andaluza conocida, para distancia local cuando el levante o el poniente no aprietan.",
    flying: "Un flujo fuerte del este o del oeste anula el día térmico. La amplitud de rachas es la pista del modelo.",
    season: "De otoño a primavera es la temporada principal; el pleno verano suele ser demasiado cálido y ventoso.",
  })),
  site("piedrahita", "ES", 40.462, -5.327, {
    name: "Piedrahíta",
    area: "Ávila, Spain",
    short: "Sierra de Gredos cross-country area.",
    overview: "Piedrahíta, on the north side of the Sierra de Gredos, is one of Spain’s classic cross-country areas.",
    flying: "A stable morning can still overdevelop. CAPE in the caution band is a reason to plan an early landing, not a promise of a long flight.",
    season: "Late spring and summer, with strong afternoon cycles.",
  }, es({
    name: "Piedrahíta",
    area: "Ávila, España",
    short: "Zona de cross en la Sierra de Gredos.",
    overview: "Piedrahíta, en la cara norte de Gredos, es una de las zonas clásicas de cross en España.",
    flying: "Una mañana estable puede sobredesarrollar. Un CAPE en cautela es motivo para planear un aterrizaje temprano.",
    season: "Finales de primavera y verano, con ciclos fuertes por la tarde.",
  })),
  site("ager", "ES", 41.999, 0.765, {
    name: "Àger",
    area: "Montsec, Catalonia",
    short: "Montsec south face, a benchmark Spanish flatland-edge site.",
    overview: "Àger on the Montsec is a benchmark Catalan site, with a south face over the reservoir and long cross-country potential.",
    flying: "South wind on the wall is the working case. Too much south becomes rowdy; the gust line is there to show that.",
    season: "Spring and autumn are reliable; summer works early in the day.",
  }, es({
    name: "Àger",
    area: "Montsec, Cataluña",
    short: "Cara sur del Montsec, referencia del vuelo en España.",
    overview: "Àger, en el Montsec, es una referencia catalana, con cara sur sobre el embalse y potencial de cross.",
    flying: "El sur en la pared es el caso que funciona. Demasiado sur se vuelve movido; la línea de rachas lo muestra.",
    season: "Primavera y otoño son fiables; en verano se vuela pronto.",
  })),
  site("castejon-de-sos", "ES", 42.512, 0.492, {
    name: "Castejón de Sos",
    area: "Benasque, Aragón",
    short: "Central Pyrenees launch in the Benasque valley.",
    overview: "Castejón de Sos is a central Pyrenean launch in the Benasque valley, used for mountain cross-country.",
    flying: "Valley wind up the Ésera can be stronger than the free-air model. If the reasons mention strong wind, believe them.",
    season: "June to September, once the high launches are clear of snow.",
  }, es({
    name: "Castejón de Sos",
    area: "Benasque, Aragón",
    short: "Despegue del Pirineo central en el valle de Benasque.",
    overview: "Castejón de Sos es un despegue del Pirineo central en el valle de Benasque, para cross de montaña.",
    flying: "El viento de valle por el Ésera puede ser más fuerte que el modelo. Si los motivos hablan de viento fuerte, hazles caso.",
    season: "De junio a septiembre, cuando los despegues altos están sin nieve.",
  })),
  site("el-yelmo", "ES", 38.27, -2.648, {
    name: "El Yelmo",
    area: "Sierra de Segura, Jaén",
    short: "South-facing wall in the Sierra de Segura.",
    overview: "El Yelmo is a south-facing wall in the Sierra de Segura, flown for distance over the olive country when the airmass is dry.",
    flying: "A wet or hazy day lowers visibility below the conservative limits even if the wind looks kind.",
    season: "Autumn, winter, and spring; summer is often unstable.",
  }, es({
    name: "El Yelmo",
    area: "Sierra de Segura, Jaén",
    short: "Pared sur en la Sierra de Segura.",
    overview: "El Yelmo es una pared sur en la Sierra de Segura, para distancia sobre el olivar cuando la masa de aire está seca.",
    flying: "Un día húmedo o turbio baja la visibilidad por debajo de los límites prudentes aunque el viento parezca amable.",
    season: "Otoño, invierno y primavera; el verano suele ser inestable.",
  })),
  site("ainsa", "ES", 42.417, 0.137, {
    name: "Aínsa",
    area: "Sobrarbe, Aragón",
    short: "Southern Pyrenees thermal area around the old town.",
    overview: "Aínsa is a southern Pyrenees flying area, with launches around the Sobrarbe used for thermal cross-country.",
    flying: "Several faces exist. The reference coordinate is a forecast point for the area, not every takeoff.",
    season: "Spring through early autumn.",
  }, es({
    name: "Aínsa",
    area: "Sobrarbe, Aragón",
    short: "Zona térmica del Pirineo sur junto al casco antiguo.",
    overview: "Aínsa es una zona de vuelo del Pirineo sur, con despegues en el Sobrarbe para cross térmico.",
    flying: "Hay varias caras. La coordenada de referencia es un punto de pronóstico del área, no cada despegue.",
    season: "De primavera a principios de otoño.",
  })),
  site("linhares", "PT", 40.538, -7.462, {
    name: "Linhares da Beira",
    area: "Guarda, Portugal",
    short: "Granite castle hill in the Beira interior.",
    overview: "Linhares da Beira is a granite launch in inland Portugal, used for thermal flights along the Serra da Estrela approach.",
    flying: "Inland summer days overdevelop. A high CAPE caution is a reason to be on the ground early.",
    season: "Spring and early summer, plus stable autumn days.",
  }, pt({
    name: "Linhares da Beira",
    area: "Guarda, Portugal",
    short: "Colina de granito na Beira interior.",
    overview: "Linhares da Beira é uma descolagem de granito no interior, para voos térmicos na aproximação à Serra da Estrela.",
    flying: "Os dias de verão no interior sobredesenvolvem. Um aviso de CAPE alto é motivo para estar no chão cedo.",
    season: "Primavera e início do verão, mais dias estáveis de outono.",
  })),
  site("serra-da-estrela", "PT", 40.322, -7.613, {
    name: "Serra da Estrela",
    area: "Torre, Portugal",
    short: "The highest massif in mainland Portugal.",
    overview: "Serra da Estrela around Torre is Portugal’s highest flying ground, cold and windy even when the coast is calm.",
    flying: "Wind at the summit is often stronger than in the valleys below. Do not assume a coastal reading applies here.",
    season: "Late spring to early autumn; winter is snow and ice.",
  }, pt({
    name: "Serra da Estrela",
    area: "Torre, Portugal",
    short: "O maciço mais alto de Portugal continental.",
    overview: "A Serra da Estrela junto à Torre é o terreno de voo mais alto do país, frio e ventoso mesmo com a costa calma.",
    flying: "O vento no cume é muitas vezes mais forte do que nos vales. Uma leitura costeira não vale aqui.",
    season: "Do fim da primavera ao início do outono; o inverno é neve e gelo.",
  })),
  site("achadas-da-cruz", "PT", 32.851, -17.213, {
    name: "Achadas da Cruz",
    area: "Madeira, Portugal",
    short: "Cliff launch on the north-west coast of Madeira.",
    overview: "Achadas da Cruz is a Madeira cliff launch on the north-west coast, flown in trade-wind regimes when the cliff is working.",
    flying: "Trade wind against the cliff is a local compression the 10 m grid only approximates. Visibility in cloud on the ridge is a no-go in the rules.",
    season: "Year-round trade winds, with wetter winter weeks.",
  }, pt({
    name: "Achadas da Cruz",
    area: "Madeira, Portugal",
    short: "Descolagem de falésia na costa noroeste da Madeira.",
    overview: "Achadas da Cruz é uma falésia na costa noroeste da Madeira, voada com alísios quando a parede trabalha.",
    flying: "O alísio contra a falésia é uma compressão local que a grelha de 10 m só aproxima. Visibilidade na nuvem da cumeeira é no-go nas regras.",
    season: "Alísios o ano todo, com semanas de inverno mais húmidas.",
  })),
  site("aljezur", "PT", 37.319, -8.803, {
    name: "Aljezur",
    area: "Algarve, Portugal",
    short: "West Algarve coastal and ridge flying.",
    overview: "Aljezur is a west Algarve area where coastal wind and small ridges are used when the sea breeze is organised.",
    flying: "A fresh onshore breeze can exceed the conservative wind limit even on a sunny day.",
    season: "Spring and autumn sea-breeze days; summer afternoons are often too windy.",
  }, pt({
    name: "Aljezur",
    area: "Algarve, Portugal",
    short: "Voo costeiro e de cume no barlavento algarvio.",
    overview: "Aljezur é uma zona do barlavento onde o vento costeiro e pequenas cumeadas se usam quando a brisa está organizada.",
    flying: "Uma brisa de mar fresca pode passar o limite prudente de vento mesmo num dia de sol.",
    season: "Dias de brisa na primavera e no outono; as tardes de verão são muitas vezes ventosas demais.",
  })),
  site("foia", "PT", 37.315, -8.596, {
    name: "Fóia",
    area: "Monchique, Algarve",
    short: "Highest point of the Serra de Monchique.",
    overview: "Fóia is the high point of the Serra de Monchique, a southern Portugal launch above the Algarve coast.",
    flying: "Coastal cloud can cap the hill while the beach stays clear. Visibility under 5 km is treated as no-go.",
    season: "Spring and autumn; summer brings heat and a strong breeze.",
  }, pt({
    name: "Fóia",
    area: "Monchique, Algarve",
    short: "Ponto mais alto da Serra de Monchique.",
    overview: "A Fóia é o ponto alto da Serra de Monchique, uma descolagem do sul acima da costa algarvia.",
    flying: "A nuvem costeira pode tapar o monte com a praia ainda limpa. Visibilidade abaixo de 5 km é tratada como no-go.",
    season: "Primavera e outono; o verão traz calor e brisa forte.",
  })),
  site("miranda-do-corvo", "PT", 40.093, -8.332, {
    name: "Miranda do Corvo",
    area: "Serra da Lousã, Portugal",
    short: "Central Portugal ridge near Coimbra.",
    overview: "Miranda do Corvo sits on the Serra da Lousã approach, a central Portugal area for local soaring.",
    flying: "Light morning wind may fail the minimum-wind filter. That is a model limit for a predictable foot launch, not a claim about ground handling skill.",
    season: "Spring through autumn.",
  }, pt({
    name: "Miranda do Corvo",
    area: "Serra da Lousã, Portugal",
    short: "Cumeada do centro de Portugal, perto de Coimbra.",
    overview: "Miranda do Corvo fica na aproximação à Serra da Lousã, uma zona do centro para voo local.",
    flying: "Vento fraco de manhã pode falhar o filtro de vento mínimo. É um limite do modelo para uma descolagem a pé previsível.",
    season: "Da primavera ao outono.",
  })),
  site("rana", "CZ", 50.408, 13.771, {
    name: "Raná",
    area: "České středohoří, Czechia",
    short: "Volcanic hill in the Bohemian Central Uplands.",
    overview: "Raná is a volcanic hill in northern Bohemia, one of Czechia’s most used training and soaring hills.",
    flying: "Several faces exist around the hill. The reference point is the summit, so check which side the wind is actually on.",
    season: "Spring to autumn; winter soaring happens on dry, windy days.",
  }, cs({
    name: "Raná",
    area: "České středohoří",
    short: "Sopečný kopec v Českém středohoří.",
    overview: "Raná je sopečný kopec v severních Čechách, jeden z nejpoužívanějších cvičných a svahových kopců v Česku.",
    flying: "Kolem kopce je víc svahů. Referenční bod je vrchol, proto ověř, na kterou stranu vítr skutečně fouká.",
    season: "Od jara do podzimu; v zimě se lítá za suchých větrných dnů.",
  })),
  site("kozakov", "CZ", 50.595, 15.263, {
    name: "Kozákov",
    area: "Bohemian Paradise, Czechia",
    short: "Ridge between Turnov and Semily.",
    overview: "Kozákov is a ridge in the Bohemian Paradise, used for soaring when the wind is on the south or west slopes.",
    flying: "An off-slope wind looks acceptable in speed and still produces no ridge lift. The score cannot see the slope aspect.",
    season: "Mainly April to October.",
  }, cs({
    name: "Kozákov",
    area: "Český ráj",
    short: "Hřeben mezi Turnovem a Semily.",
    overview: "Kozákov je hřeben v Českém ráji, pro svahové létání když vítr sedí na jižní nebo západní svahy.",
    flying: "Vítr mimo svah může mít přijatelnou rychlost a přesto nedá svahový vztlak. Skóre nevidí orientaci svahu.",
    season: "Hlavně duben až říjen.",
  })),
  site("bezdez", "CZ", 50.539, 14.72, {
    name: "Bezděz",
    area: "Machovo jezero, Czechia",
    short: "Castle hill above the Mácha lake country.",
    overview: "Bezděz is a castle hill in northern Bohemia, flown as a local soaring site above the lake country.",
    flying: "Lake breeze and hill wind can oppose each other by early afternoon. Re-check the hourly samples.",
    season: "Spring through early autumn.",
  }, cs({
    name: "Bezděz",
    area: "Máchovo jezero",
    short: "Hradní kopec nad Máchovým krajem.",
    overview: "Bezděz je hradní kopec v severních Čechách, místní svahové létání nad jezerní krajinou.",
    flying: "Vánek od jezera a vítr na kopci se odpoledne mohou postavit proti sobě. Znovu čti hodinové vzorky.",
    season: "Od jara do začátku podzimu.",
  })),
  site("dolni-morava", "CZ", 50.122, 16.799, {
    name: "Dolní Morava",
    area: "Králický Sněžník, Czechia",
    short: "Eastern Bohemia mountain site near the Polish border.",
    overview: "Dolní Morava lies under Králický Sněžník, an eastern Bohemian mountain site shared in spirit with the Polish side of the massif.",
    flying: "Mountain wind is often stronger than the valley forecast pilots check first. Use this summit reference, not a town in the valley.",
    season: "Summer and early autumn; winter is a ski resort.",
  }, cs({
    name: "Dolní Morava",
    area: "Králický Sněžník",
    short: "Horský terén ve východních Čechách u polské hranice.",
    overview: "Dolní Morava leží pod Králickým Sněžníkem, horský terén na česko-polském masivu.",
    flying: "Horský vítr bývá silnější než údolní předpověď. Použij tuto vrcholovou referenci, ne město v údolí.",
    season: "Léto a začátek podzimu; v zimě je to lyžařské středisko.",
  })),
  site("jested", "CZ", 50.733, 14.985, {
    name: "Ještěd",
    area: "Liberec, Czechia",
    short: "Summit above Liberec.",
    overview: "Ještěd is the summit above Liberec, a local soaring hill with a wide view over northern Bohemia.",
    flying: "North and west winds are the usual working directions. A pretty score with the wind on the wrong side still means no ridge.",
    season: "April to October.",
  }, cs({
    name: "Ještěd",
    area: "Liberec",
    short: "Vrchol nad Libercem.",
    overview: "Ještěd je vrchol nad Libercem, místní svah s širokým výhledem na severní Čechy.",
    flying: "Severní a západní vítr jsou obvyklé směry. Hezké skóre při větru na špatnou stranu pořád znamená, že svah nefunguje.",
    season: "Duben až říjen.",
  })),
  site("cerna-hora", "CZ", 50.652, 15.743, {
    name: "Černá hora",
    area: "Krkonoše, Czechia",
    short: "Krkonoše ridge above Janské Lázně.",
    overview: "Černá hora is a Krkonoše ridge above Janské Lázně, flown in mountain wind when the national-park rules allow.",
    flying: "Park rules and a wind that is too strong for the trees are outside the score. The model only rates the weather sample.",
    season: "Summer months; the ridge is a winter ski hill.",
  }, cs({
    name: "Černá hora",
    area: "Krkonoše",
    short: "Hřeben Krkonoš nad Janskými Lázněmi.",
    overview: "Černá hora je krkonošský hřeben nad Janskými Lázněmi, za horského větru když to pravidla parku dovolí.",
    flying: "Pravidla parku a vítr příliš silný pro les jsou mimo skóre. Model hodnotí jen vzorek počasí.",
    season: "Letní měsíce; v zimě je hřeben sjezdovka.",
  })),
  site("donovaly", "SK", 48.878, 19.228, {
    name: "Donovaly",
    area: "Low Tatras, Slovakia",
    short: "Saddle between the Low Tatras and Veľká Fatra.",
    overview: "Donovaly is the saddle between the Low Tatras and Veľká Fatra, a Slovak mountain site used in summer wind.",
    flying: "Saddle wind accelerates. A moderate valley reading can be a strong saddle reading at this coordinate.",
    season: "June to September.",
  }, sk({
    name: "Donovaly",
    area: "Nízke Tatry, Slovensko",
    short: "Sedlo medzi Nízkymi Tatrami a Veľkou Fatrou.",
    overview: "Donovaly sú sedlo medzi Nízkymi Tatrami a Veľkou Fatrou, horský terén na letný vietor.",
    flying: "Vietor v sedle zrýchľuje. Mierny údaj z doliny môže byť na tejto súradnici silný.",
    season: "Jún až september.",
  })),
  site("stranik", "SK", 49.213, 18.783, {
    name: "Straník",
    area: "Žilina, Slovakia",
    short: "Hill above Žilina, one of Slovakia’s busiest schools.",
    overview: "Straník above Žilina is one of Slovakia’s busiest training hills, with several faces around the summit.",
    flying: "Training hills still fail the strong-wind and gust filters. A green score is not a student briefing.",
    season: "April to October.",
  }, sk({
    name: "Straník",
    area: "Žilina, Slovensko",
    short: "Kopec nad Žilinou, jedna z najrušnejších škôl.",
    overview: "Straník nad Žilinou je jeden z najrušnejších cvičných kopcov, s viacerými stranami okolo vrcholu.",
    flying: "Aj cvičný kopec neprejde filtrami silného vetra a nárazov. Zelené skóre nie je brífing pre žiaka.",
    season: "Apríl až október.",
  })),
  site("martinske-hole", "SK", 49.098, 18.848, {
    name: "Martinské hole",
    area: "Martin, Slovakia",
    short: "Ridge above Martin in the Malá Fatra approach.",
    overview: "Martinské hole is the ridge above Martin, used for local soaring toward the Malá Fatra.",
    flying: "West and north-west winds are the usual working directions. Check the direction line, not only the speed.",
    season: "Late spring through early autumn.",
  }, sk({
    name: "Martinské hole",
    area: "Martin, Slovensko",
    short: "Hrebeň nad Martinom smerom na Malú Fatru.",
    overview: "Martinské hole sú hrebeň nad Martinom na miestne svahovanie smerom na Malú Fatru.",
    flying: "Západný a severozápadný vietor sú obvyklé smery. Čítaj smer, nie len rýchlosť.",
    season: "Neskorá jar až skorá jeseň.",
  })),
  site("krizna", "SK", 48.873, 19.083, {
    name: "Krížna",
    area: "Veľká Fatra, Slovakia",
    short: "Veľká Fatra summit south of Donovaly.",
    overview: "Krížna is a Veľká Fatra summit south of Donovaly, flown for mountain soaring in summer.",
    flying: "Summit coordinates read stronger wind than the meadow below. Landings are a local problem the model does not solve.",
    season: "Summer, once snow has left the ridge.",
  }, sk({
    name: "Krížna",
    area: "Veľká Fatra, Slovensko",
    short: "Vrchol Veľkej Fatry južne od Donovál.",
    overview: "Krížna je vrchol Veľkej Fatry južne od Donovál, na horské svahovanie v lete.",
    flying: "Vrcholové súradnice čítajú silnejší vietor než lúka pod nimi. Pristátia model nerieši.",
    season: "Leto, keď z hrebeňa zíde sneh.",
  })),
  site("velka-raca", "SK", 49.414, 18.968, {
    name: "Veľká Rača",
    area: "Kysuce, Slovakia",
    short: "Kysuce ridge on the Czech–Slovak border.",
    overview: "Veľká Rača is a Kysuce ridge on the Czech–Slovak border, a grassy mountain site in north-west Slovakia.",
    flying: "Border ridges take a clean wind and a cross-wind equally in the model. Only the hill shows which one you have.",
    season: "June to September.",
  }, sk({
    name: "Veľká Rača",
    area: "Kysuce, Slovensko",
    short: "Kysucký hrebeň na česko-slovenskej hranici.",
    overview: "Veľká Rača je kysucký hrebeň na hranici, trávnatý horský terén na severozápade Slovenska.",
    flying: "Hraničný hrebeň berie v modeli čistý vietor aj bočný vietor rovnako. Len kopec ukáže, ktorý máš.",
    season: "Jún až september.",
  })),
  site("chopok", "SK", 48.943, 19.59, {
    name: "Chopok",
    area: "Low Tatras, Slovakia",
    short: "High Low Tatras shoulder, flown in settled summer weather.",
    overview: "Chopok is a high shoulder of the Low Tatras. It is a serious mountain site, not a training hill, and only in settled weather.",
    flying: "Wind, gusts, and cloud on the ridge fail the conservative filters more often than a valley site. That is the point of the score.",
    season: "High summer when the south side is clear of snow.",
  }, sk({
    name: "Chopok",
    area: "Nízke Tatry, Slovensko",
    short: "Vysoké sedlo Nízkych Tatier, len v ustálenom letnom počasí.",
    overview: "Chopok je vysoké plece Nízkych Tatier. Je to vážny horský terén, nie cvičný kopec, a len v ustálenom počasí.",
    flying: "Vietor, nárazy a oblačnosť na hrebeni častejšie neprejdú filtrami než dolinový terén. Presne na to je skóre.",
    season: "Vrchol leta, keď je južná strana bez snehu.",
  })),
  site("lijak", "SI", 45.968, 13.724, {
    name: "Lijak",
    area: "Vipava valley, Slovenia",
    short: "The classic Slovenian west-facing ridge above the Vipava valley.",
    overview: "Lijak is the classic Slovenian ridge above the Vipava valley, flown in west and south-west wind.",
    flying: "Bora days are a different wind from a thermal west. If the speed is high and the direction is north-east, it is not a Lijak day.",
    season: "Spring and autumn west winds; summer thermals on lighter days.",
  }, sl({
    name: "Lijak",
    area: "Vipavska dolina, Slovenija",
    short: "Klasičen slovenski zahodni greben nad Vipavsko dolino.",
    overview: "Lijak je klasičen slovenski greben nad Vipavsko dolino, v zahodnem in jugozahodnem vetru.",
    flying: "Burja je drug veter kot termični zahodnik. Če je hitrost visoka in smer severovzhod, to ni dan za Lijak.",
    season: "Zahodniki spomladi in jeseni; poleti termika ob šibkejših dnevih.",
  })),
  site("kobala", "SI", 46.185, 13.578, {
    name: "Kobala",
    area: "Tolmin, Slovenia",
    short: "Tolmin launch above the Soča valley.",
    overview: "Kobala above Tolmin is a Soča-valley launch used for local and cross-country flights toward the Julian Alps.",
    flying: "Valley wind up the Soča strengthens through the day. The favorable-until line is a model hint, not a clearance to stay out.",
    season: "May to September.",
  }, sl({
    name: "Kobala",
    area: "Tolmin, Slovenija",
    short: "Tolminsko vzletišče nad dolino Soče.",
    overview: "Kobala nad Tolminom je vzletišče v dolini Soče za lokalne lete in prelete proti Julijcem.",
    flying: "Dolinski veter po Soči čez dan krepi. Vrstica „ugodno do“ je namig modela, ne dovoljenje za ostanek v zraku.",
    season: "Maj do september.",
  })),
  site("sorica", "SI", 46.221, 14.028, {
    name: "Sorica",
    area: "Škofja Loka hills, Slovenia",
    short: "Grassy launch above the Selca valley.",
    overview: "Sorica is a grassy launch above the Selca valley, one of the most used Slovenian sites for thermals and short cross-country.",
    flying: "A humid afternoon with high CAPE is the day the score is meant to mark down, even if the morning looked easy.",
    season: "April to October.",
  }, sl({
    name: "Sorica",
    area: "Škofjeloško hribovje, Slovenija",
    short: "Travnato vzletišče nad Selško dolino.",
    overview: "Sorica je travnato vzletišče nad Selško dolino, eno najbolj uporabljanih slovenskih vzletišč za termiko in kratke prelete.",
    flying: "Vlažno popoldne z visokim CAPE je dan, ki ga mora ocena znižati, tudi če je jutro videti lahko.",
    season: "April do oktober.",
  })),
  site("vogel", "SI", 46.238, 13.837, {
    name: "Vogel",
    area: "Bohinj, Slovenia",
    short: "High launch above Lake Bohinj.",
    overview: "Vogel is the high launch above Lake Bohinj, an alpine site with a steep departure toward the lake.",
    flying: "Lake breeze and ridge wind meet here. Gust spread matters as much as the mean speed.",
    season: "Snow-free summer months.",
  }, sl({
    name: "Vogel",
    area: "Bohinj, Slovenija",
    short: "Visoko vzletišče nad Bohinjskim jezerom.",
    overview: "Vogel je visoko vzletišče nad Bohinjskim jezerom, alpski teren s strmim odhodom proti jezeru.",
    flying: "Tu se srečata jezerski vetrič in grebenski veter. Razpon sunkov šteje toliko kot povprečna hitrost.",
    season: "Poletni meseci brez snega.",
  })),
  site("kovk", "SI", 45.898, 13.908, {
    name: "Kovk",
    area: "Vipava, Slovenia",
    short: "South of the Vipava valley, often paired with Lijak.",
    overview: "Kovk is a launch south of the Vipava valley, often compared with Lijak when pilots choose which face the wind is on.",
    flying: "Open both reference points if you are choosing between them. The better score is still not the face that is working.",
    season: "Same west-wind season as the rest of the Vipava valley.",
  }, sl({
    name: "Kovk",
    area: "Vipava, Slovenija",
    short: "Južno od Vipavske doline, pogosto poleg Lijaka.",
    overview: "Kovk je vzletišče južno od Vipavske doline, pogosto v primerjavi z Lijakom, ko piloti izbirajo stran vetra.",
    flying: "Odpri obe referenčni točki, če izbiraš med njima. Boljša ocena še ni stran, ki dela.",
    season: "Ista sezona zahodnikov kot preostala Vipavska dolina.",
  })),
  site("ratitovec", "SI", 46.247, 14.083, {
    name: "Ratitovec",
    area: "Jelovica, Slovenia",
    short: "High meadow on the Jelovica plateau.",
    overview: "Ratitovec is a high meadow on the Jelovica plateau, used for thermal flights toward the Julian edge.",
    flying: "Plateau wind is exposed. If gusts fail the filter, the meadow will feel at least that windy.",
    season: "Summer and early autumn.",
  }, sl({
    name: "Ratitovec",
    area: "Jelovica, Slovenija",
    short: "Visok travnik na Jelovici.",
    overview: "Ratitovec je visok travnik na Jelovici, za termične lete proti julijskemu robu.",
    flying: "Veter na planoti je izpostavljen. Če sunki ne prestanejo filtra, bo travnik vsaj tako vetroven.",
    season: "Poletje in zgodnja jesen.",
  })),
  site("coo", "BE", 50.39, 5.872, {
    name: "Coo",
    area: "Ardennes, Liège",
    short: "Ardennes ridge above the Amblève waterfalls.",
    overview: "Coo is an Ardennes ridge above the Amblève, one of Belgium’s regular soaring hills when the wind is on the face.",
    flying: "Wooded ridges hide rotor. A clean 10 m wind in the model can still be messy at the tree line.",
    season: "Spring through autumn.",
  }, nl({
    name: "Coo",
    area: "Ardennen, Luik",
    short: "Ardenner kam boven de watervallen van de Amblève.",
    overview: "Coo is een Ardenner kam boven de Amblève, een van de vaste Belgische hellingen als de wind erop staat.",
    flying: "Beboste kammen verbergen rotor. Een schone 10 m-wind in het model kan aan de bosrand alsnog rommelig zijn.",
    season: "Lente tot herfst.",
  })),
  site("malchamps", "BE", 50.473, 5.91, {
    name: "Malchamps",
    area: "Spa, Liège",
    short: "High plateau site near Spa.",
    overview: "Malchamps near Spa is a high Ardennes plateau site, flown in west and south-west winds.",
    flying: "Plateau sites take the full wind. If the score says the sustained wind is too strong, the plateau will not be kinder.",
    season: "April to October.",
  }, nl({
    name: "Malchamps",
    area: "Spa, Luik",
    short: "Hoog plateaugebied bij Spa.",
    overview: "Malchamps bij Spa is een hoog Ardenner plateau, gevlogen bij westen- en zuidwestenwind.",
    flying: "Een plateau pakt de volle wind. Als de score zegt dat de wind te sterk is, wordt het plateau niet vriendelijker.",
    season: "April tot oktober.",
  })),
  site("baraque-de-fraiture", "BE", 50.253, 5.732, {
    name: "Baraque de Fraiture",
    area: "Ardennes, Luxembourg province",
    short: "One of the highest points in Belgium.",
    overview: "Baraque de Fraiture is one of the highest points in Belgium, a cold, open Ardennes site.",
    flying: "Exposure means gusts. The gust-minus-wind spread is the number to read before walking up.",
    season: "Warmer months; winter is often in cloud.",
  }, nl({
    name: "Baraque de Fraiture",
    area: "Ardennen, Luxemburg",
    short: "Een van de hoogste punten van België.",
    overview: "Baraque de Fraiture is een van de hoogste punten van België, een koud en open Ardenner terrein.",
    flying: "Open terrein betekent vlagen. Lees de spreiding tussen wind en vlaag voor je omhoog loopt.",
    season: "Warmere maanden; de winter zit vaak in de wolken.",
  })),
  site("ovifat", "BE", 50.478, 6.082, {
    name: "Ovifat",
    area: "Hautes Fagnes, Liège",
    short: "High fenland ridge near the German border.",
    overview: "Ovifat sits on the Hautes Fagnes near the German border, a high, often cloudy Belgian ridge.",
    flying: "Cloud on the fens drops visibility quickly. Under 5 km the automated rules say no-go.",
    season: "Late spring to early autumn, between wet spells.",
  }, nl({
    name: "Ovifat",
    area: "Hoge Venen, Luik",
    short: "Hoge venkam dicht bij de Duitse grens.",
    overview: "Ovifat ligt op de Hoge Venen bij de Duitse grens, een hoge en vaak bewolkte Belgische kam.",
    flying: "Wolken op de venen laten het zicht snel zakken. Onder 5 km zeggen de regels no-go.",
    season: "Late lente tot vroege herfst, tussen natte perioden.",
  })),
  site("la-roche", "BE", 50.183, 5.575, {
    name: "La Roche-en-Ardenne",
    area: "Ourthe valley, Belgium",
    short: "Ardennes town with nearby ridge launches.",
    overview: "La Roche-en-Ardenne is the Ourthe-valley town whose nearby ridges are used for local Belgian soaring.",
    flying: "The reference point stands for the area, not a single meadow. Ask which face is briefed that day.",
    season: "Spring through autumn.",
  }, nl({
    name: "La Roche-en-Ardenne",
    area: "Ourthedal, België",
    short: "Ardennendorp met hellingen in de buurt.",
    overview: "La Roche-en-Ardenne is het Ourthedorp waarvan de nabije kammen voor lokaal Belgisch hellingvliegen worden gebruikt.",
    flying: "Het referentiepunt staat voor het gebied, niet voor één weide. Vraag welke kant die dag gebriefd is.",
    season: "Lente tot herfst.",
  })),
  site("dinant", "BE", 50.261, 4.912, {
    name: "Dinant",
    area: "Meuse valley, Belgium",
    short: "Meuse-valley cliffs and small ridges.",
    overview: "Dinant on the Meuse is a southern Belgian area where small ridges and cliffs are flown in a suitable wind.",
    flying: "Valley channelling along the Meuse can raise the speed above the regional forecast. Read the local sample.",
    season: "April to October.",
  }, nl({
    name: "Dinant",
    area: "Maasvallei, België",
    short: "Kliffen en kleine kammen in de Maasvallei.",
    overview: "Dinant aan de Maas is een Zuid-Belgisch gebied waar kleine kammen en kliffen bij geschikte wind worden gevlogen.",
    flying: "Kanaalwerking langs de Maas kan de snelheid boven de regionale verwachting tillen. Lees het lokale sample.",
    season: "April tot oktober.",
  })),
  site("wijk-aan-zee", "NL", 52.494, 4.593, {
    name: "Wijk aan Zee",
    area: "North Holland coast",
    short: "Dune soaring on the Dutch North Sea coast.",
    overview: "Wijk aan Zee is a North Sea dune site used for coastal soaring when the wind is onshore and within club limits.",
    flying: "Onshore wind that is flyable in the dunes can still be above the conservative sustained-wind filter. The filter is not the club rule, and the club rule is not the filter.",
    season: "Year-round wind; winter days are short.",
  }, nl({
    name: "Wijk aan Zee",
    area: "Noord-Hollandse kust",
    short: "Duinen op de Nederlandse Noordzeekust.",
    overview: "Wijk aan Zee is een Noordzeeduinterrein voor kustvliegen als de wind aanlandig is en binnen de clubgrenzen valt.",
    flying: "Aanlandige wind die in de duinen vliegbaar lijkt kan nog boven het voorzichtige filter zitten. Het filter is niet de clubregel.",
    season: "Wind het hele jaar; winterdagen zijn kort.",
  })),
  site("zoutelande", "NL", 51.501, 3.484, {
    name: "Zoutelande",
    area: "Walcheren, Zeeland",
    short: "Zeeland dune coast on the Western Scheldt side.",
    overview: "Zoutelande is a Zeeland dune coast used when the wind is on the beach and the tide and local rules allow.",
    flying: "Sea wind is often stronger than an inland reading. Use this coastal coordinate, not a town 20 km inland.",
    season: "Windy months year-round; summer sea breezes are reliable and sometimes too strong.",
  }, nl({
    name: "Zoutelande",
    area: "Walcheren, Zeeland",
    short: "Zeeuwse duinenkust aan de Westerschelde.",
    overview: "Zoutelande is een Zeeuwse duinenkust als de wind op het strand staat en tij en lokale regels het toelaten.",
    flying: "Zeewind is vaak sterker dan een meting landinwaarts. Gebruik deze kustcoördinaat, niet een dorp 20 km het land in.",
    season: "Winderige maanden het hele jaar; zomerse zeewind is betrouwbaar en soms te sterk.",
  })),
  site("schoorl", "NL", 52.705, 4.694, {
    name: "Schoorl",
    area: "North Holland dunes",
    short: "High dunes between Alkmaar and the sea.",
    overview: "Schoorl’s dunes are among the highest in the Netherlands, used for coastal soaring in an onshore wind.",
    flying: "Dune compression is local. The 10 m wind is a grid value, not the accelerated flow in the slot you intend to use.",
    season: "Year-round, with the strongest sea breezes in spring and summer.",
  }, nl({
    name: "Schoorl",
    area: "Noord-Hollandse duinen",
    short: "Hoge duinen tussen Alkmaar en de zee.",
    overview: "De duinen van Schoorl behoren tot de hoogste van Nederland, voor kustvliegen bij aanlandige wind.",
    flying: "Duinencompressie is lokaal. De 10 m-wind is een roosterwaarde, niet de versnelde stroming in de geul die je wilt gebruiken.",
    season: "Het hele jaar, met de sterkste zeewind in lente en zomer.",
  })),
  site("bergen-aan-zee", "NL", 52.664, 4.632, {
    name: "Bergen aan Zee",
    area: "North Holland coast",
    short: "Coastal dunes just south of Schoorl.",
    overview: "Bergen aan Zee is the coastal dune strip south of Schoorl, flown in the same North Sea regimes.",
    flying: "If Schoorl and Bergen disagree in the model, the wind is marginal. Treat disagreement as a reason to look at both hourly lists.",
    season: "Same coastal season as Schoorl.",
  }, nl({
    name: "Bergen aan Zee",
    area: "Noord-Hollandse kust",
    short: "Kustduinen net ten zuiden van Schoorl.",
    overview: "Bergen aan Zee is de duinstrook ten zuiden van Schoorl, gevlogen in dezelfde Noordzeeregimes.",
    flying: "Als Schoorl en Bergen in het model uiteenlopen, is de wind marginaal. Bekijk dan beide uurlijsten.",
    season: "Hetzelfde kustseizoen als Schoorl.",
  })),
  site("texel", "NL", 53.098, 4.774, {
    name: "Texel",
    area: "Wadden Islands, Netherlands",
    short: "North Sea island dunes on the Wadden side.",
    overview: "Texel’s dunes are a Wadden Sea island site, exposed to North Sea wind with few trees to mark the flow.",
    flying: "Island wind is clean and often strong. The conservative upper wind limit will fail many good-looking sunny days.",
    season: "Year-round wind; summer has the longest soaring days.",
  }, nl({
    name: "Texel",
    area: "Waddeneilanden, Nederland",
    short: "Noordzeeduinen op een Waddeneiland.",
    overview: "De duinen van Texel zijn een Waddeneiland, blootgesteld aan Noordzeewind met weinig bomen die de stroming tonen.",
    flying: "Eilandwind is schoon en vaak sterk. De voorzichtige bovengrens haalt veel zonnige dagen niet.",
    season: "Wind het hele jaar; de zomer heeft de langste vliegdagen.",
  })),
  site("scheveningen", "NL", 52.108, 4.276, {
    name: "Scheveningen",
    area: "The Hague coast",
    short: "Urban North Sea beach and dune edge.",
    overview: "Scheveningen is the Hague coast, where dune and beach soaring depend on an organised onshore wind and local access rules.",
    flying: "A beach reading and a dune reading differ. This coordinate is the coast, not the city centre.",
    season: "Wind year-round; sea breeze is strongest from spring to early autumn.",
  }, nl({
    name: "Scheveningen",
    area: "Kust van Den Haag",
    short: "Stedelijk Noordzeestrand en duinrand.",
    overview: "Scheveningen is de Haagse kust, waar duin- en strandvliegen afhangen van een georganiseerde aanlandige wind en lokale toegangsregels.",
    flying: "Een strandmeting en een duinmeting verschillen. Deze coördinaat is de kust, niet het stadscentrum.",
    season: "Wind het hele jaar; zeewind is het sterkst van lente tot begin herfst.",
  })),
  site("mount-leinster", "IE", 52.618, -6.779, {
    name: "Mount Leinster",
    area: "Blackstairs, Ireland",
    short: "The main inland soaring mountain on the Carlow–Wexford border.",
    overview: "Mount Leinster is the main inland soaring mountain on the Carlow–Wexford border, flown in a wind on the west or south-west faces.",
    flying: "Irish hills sit in cloud often. Visibility and a low cloud signal matter as much as the wind speed.",
    season: "Spring through autumn; winter ridges are frequently in cloud.",
  }),
  site("great-sugar-loaf", "IE", 53.152, -6.153, {
    name: "Great Sugar Loaf",
    area: "Wicklow, Ireland",
    short: "Conical Wicklow hill south of Dublin.",
    overview: "Great Sugar Loaf is the conical Wicklow hill south of Dublin, used for soaring when the wind is on a flyable face.",
    flying: "A round hill has a small working sector. The score does not know which path you will walk.",
    season: "April to October.",
  }),
  site("maulin", "IE", 53.181, -6.218, {
    name: "Maulin",
    area: "Wicklow Mountains, Ireland",
    short: "Wicklow ridge near the Great Sugar Loaf.",
    overview: "Maulin is a Wicklow ridge near the Great Sugar Loaf, a second Dublin-side option when the wind suits a different aspect.",
    flying: "Compare it with Sugar Loaf in the console if you are choosing a face. Both are forecasts, not a hill briefing.",
    season: "Spring through autumn.",
  }),
  site("benone", "IE", 55.166, -6.877, {
    name: "Benone",
    area: "County Derry coast",
    short: "North-coast dune and strand soaring.",
    overview: "Benone is a north-coast strand and dune site, flown in an onshore Atlantic wind when access allows.",
    flying: "Atlantic wind is often above a conservative inland limit. Read the sustained speed before you drive the coast road.",
    season: "Windy year-round; the longest days are late spring and summer.",
  }),
  site("knockmealdown", "IE", 52.228, -7.915, {
    name: "Knockmealdown",
    area: "Waterford–Tipperary, Ireland",
    short: "Southern inland ridge on the county border.",
    overview: "Knockmealdown is the ridge on the Waterford–Tipperary border, an inland soaring site in the south of Ireland.",
    flying: "South-west wind is the usual working direction. Cloud base on the panel is estimated, not measured.",
    season: "Late spring to early autumn.",
  }),
  site("muckish", "IE", 55.102, -7.992, {
    name: "Muckish",
    area: "Donegal, Ireland",
    short: "Flat-topped Donegal mountain.",
    overview: "Muckish is a flat-topped Donegal mountain, exposed to Atlantic weather and flown only in a settled, on-face wind.",
    flying: "Donegal wind and cloud change faster than the cache. If the day looks marginal, the mountain will not be the forgiving option.",
    season: "Summer and early autumn, between Atlantic fronts.",
  }),
  site("dingli", "MT", 35.852, 14.382, {
    name: "Dingli Cliffs",
    area: "Western Malta",
    short: "The main Maltese cliff, facing the open sea.",
    overview: "Dingli Cliffs are the main Maltese free-flight cliff, facing the open sea on the west coast.",
    flying: "A sea wind on the cliff compresses. The 10 m value is a starting point; the cliff slot is decided on the day.",
    season: "Spring and autumn sea breezes; summer afternoons are often strong.",
  }, mt({
    name: "Irdumijiet tad-Dingli",
    area: "Punent ta’ Malta",
    short: "L-irdum ewlieni ta’ Malta, jħares lejn il-baħar miftuħ.",
    overview: "L-Irdumijiet tad-Dingli huma l-irdum ewlieni għat-titjira libera f’Malta, mal-kosta tal-punent.",
    flying: "Riħ tal-baħar fuq l-irdum jiġi kkompressat. Il-valur ta’ 10 m huwa punt tat-tluq; il-kanal tal-irdum jiġi deċiż fil-ġurnata.",
    season: "Brezzi tar-rebbiegħa u tal-ħarifa; il-waranofsinhar tas-sajf spiss ikun qawwi.",
  })),
  site("mellieha", "MT", 35.956, 14.362, {
    name: "Mellieħa",
    area: "Northern Malta",
    short: "North-ridge slopes above Mellieħa bay.",
    overview: "Mellieħa’s ridge is the northern option when the wind is on the north-facing slopes rather than the Dingli sea cliff.",
    flying: "Choosing Mellieħa over Dingli is a direction decision. Open the direction line before you drive.",
    season: "Same Maltese breeze season as the west coast.",
  }, mt({
    name: "Mellieħa",
    area: "Tramuntana ta’ Malta",
    short: "Xtut tat-tramuntana fuq il-bajja tal-Mellieħa.",
    overview: "Ix-xatt tal-Mellieħa huwa l-għażla tat-tramuntana meta r-riħ ikun fuq ix-xtut tat-tramuntana u mhux fuq l-irdum tad-Dingli.",
    flying: "Li tagħżel il-Mellieħa minflok id-Dingli hija deċiżjoni tad-direzzjoni. Iftaħ il-linja tad-direzzjoni qabel issuq.",
    season: "L-istess staġun ta’ brezz ta’ Malta bħall-kosta tal-punent.",
  })),
  site("golden-bay", "MT", 35.934, 14.344, {
    name: "Golden Bay",
    area: "Għajn Tuffieħa, Malta",
    short: "North-west bay used in an onshore breeze.",
    overview: "Golden Bay and Għajn Tuffieħa are the north-west bays used when an onshore breeze is organised and not too strong.",
    flying: "Onshore flow that looks pleasant can still exceed the upper wind filter. Read the sustained speed.",
    season: "Spring and autumn; summer breezes strengthen in the afternoon.",
  }, mt({
    name: "Golden Bay",
    area: "Għajn Tuffieħa, Malta",
    short: "Bajja tal-majjistral f’brezz li ġej mill-baħar.",
    overview: "Golden Bay u Għajn Tuffieħa huma l-bajjiet tal-majjistral meta l-brezz ikun organizzat u mhux qawwi wisq.",
    flying: "Fluss mill-baħar li jidher pjaċevoli xorta jista’ jaqbeż il-filtru ta’ fuq tar-riħ. Aqra l-veloċità sostnuta.",
    season: "Rebbiegħa u ħarifa; il-brezz tas-sajf jissaħħaħ wara nofsinhar.",
  })),
  site("wardija", "MT", 35.923, 14.392, {
    name: "Wardija",
    area: "Northern Malta",
    short: "Inland ridge between the north bays and Mdina.",
    overview: "Wardija is an inland northern ridge, a Maltese option when the sea cliffs are too windy and the ridge still has a working face.",
    flying: "If the coast fails the wind filter and Wardija does not, the difference is real enough to compare — and still not a reason to skip the hill check.",
    season: "Spring through autumn.",
  }, mt({
    name: "Wardija",
    area: "Tramuntana ta’ Malta",
    short: "Xatt intern bejn il-bajjiet tat-tramuntana u l-Imdina.",
    overview: "Wardija hija xatt intern tat-tramuntana, għażla meta l-irdumijiet tal-baħar ikunu rjieħ wisq u x-xatt għad għandu wiċċ li jaħdem.",
    flying: "Jekk il-kosta tfalli l-filtru u Wardija le, id-differenza tiswa paragun — u xorta mhijiex raġuni biex taqbeż il-verifika fuq il-post.",
    season: "Mir-rebbiegħa sal-ħarifa.",
  })),
  site("qrendi", "MT", 35.835, 14.458, {
    name: "Qrendi",
    area: "Southern Malta",
    short: "South-coast limestone country near the cliffs.",
    overview: "Qrendi is southern limestone country near the sea cliffs, used when the wind is south of the Dingli sector.",
    flying: "South wind on Malta is a different day from the classic west cliff. Do not reuse a Dingli plan unchanged.",
    season: "Spring and autumn.",
  }, mt({
    name: "Qrendi",
    area: "Nofsinhar ta’ Malta",
    short: "Art tal-ġebla tal-franka fin-nofsinhar, ħdejn l-irdumijiet.",
    overview: "Il-Qrendi huwa art tal-ġebla tal-franka fin-nofsinhar, meta r-riħ ikun fin-nofsinhar tas-settur tad-Dingli.",
    flying: "Riħ tan-nofsinhar f’Malta huwa ġurnata differenti mill-irdum klassiku tal-punent. Terġax tuża pjan tad-Dingli kif inhu.",
    season: "Rebbiegħa u ħarifa.",
  })),
  site("fomm-ir-rih", "MT", 35.905, 14.333, {
    name: "Fomm ir-Riħ",
    area: "West coast, Malta",
    short: "Remote west-coast bay north of the Dingli cliffs.",
    overview: "Fomm ir-Riħ is a remote west-coast bay north of Dingli, exposed to the same sea wind with a narrower landing story.",
    flying: "Exposure and a small landing are local limits. The score only says whether the weather sample passed the filters.",
    season: "Spring and autumn sea-breeze days.",
  }, mt({
    name: "Fomm ir-Riħ",
    area: "Kosta tal-punent, Malta",
    short: "Bajja remota tal-punent fit-tramuntana tal-irdumijiet tad-Dingli.",
    overview: "Fomm ir-Riħ hija bajja remota tal-punent fit-tramuntana tad-Dingli, esposta għall-istess riħ tal-baħar b’art tal-inżul idjaq.",
    flying: "L-espożizzjoni u nżul żgħir huma limiti lokali. Il-punteġġ jgħid biss jekk il-kampjun tat-temp għaddiex mill-filtri.",
    season: "Ġranet ta’ brezz fir-rebbiegħa u fil-ħarifa.",
  })),
  site("kas", "TR", 36.202, 29.637, {
    name: "Kaş",
    area: "Antalya coast, Turkey",
    short: "Lycia coastal ridges west of Ölüdeniz.",
    overview: "Kaş is a Lycia coastal area west of Ölüdeniz, with ridge and thermal flying when the meltem is not too strong.",
    flying: "The meltem can push the sustained wind over the conservative limit on a clear day. Read the speed, not only the sun.",
    season: "Spring and autumn; midsummer afternoons are often windy.",
  }, tr({
    name: "Kaş",
    area: "Antalya kıyısı, Türkiye",
    short: "Ölüdeniz’in batısında Likya kıyı sırtları.",
    overview: "Kaş, Ölüdeniz’in batısında bir Likya kıyı bölgesidir; meltem çok güçlü değilken sırt ve termik uçuşu yapılır.",
    flying: "Meltem, açık bir günde sürekli rüzgarı temkinli sınırın üzerine çıkarabilir. Yalnızca güneşe değil hıza bak.",
    season: "İlkbahar ve sonbahar; yaz öğleden sonraları çoğu zaman rüzgarlıdır.",
  })),
  site("abant", "TR", 40.605, 31.278, {
    name: "Abant",
    area: "Bolu, Turkey",
    short: "Lake and ridge country inland from the Black Sea.",
    overview: "Abant is an inland lake-and-ridge area near Bolu, flown for local soaring away from the Aegean meltem.",
    flying: "Lake breeze and ridge wind can oppose each other. The reference point is the lake country, not a single meadow.",
    season: "Late spring through early autumn.",
  }, tr({
    name: "Abant",
    area: "Bolu, Türkiye",
    short: "Karadeniz’in iç kesiminde göl ve sırt ülkesi.",
    overview: "Abant, Bolu yakınında iç kesim göl ve sırt bölgesidir; Ege melteminden uzakta yerel sırt uçuşu için kullanılır.",
    flying: "Göl meltemi ile sırt rüzgarı birbirine karşı olabilir. Referans noktası göl çevresidir, tek bir çayır değil.",
    season: "İlkbahar sonundan sonbahar başına.",
  })),
  site("pamukkale", "TR", 37.92, 29.121, {
    name: "Pamukkale",
    area: "Denizli, Turkey",
    short: "Inland Aegean ridges above the travertines.",
    overview: "Pamukkale and the Denizli ridges are an inland Aegean flying area, thermal when the airmass is dry and not too windy.",
    flying: "Summer inland CAPE is often high. A caution on instability is a reason to shorten the flight, not a scenic bonus.",
    season: "Spring and autumn; high summer overdevelops.",
  }, tr({
    name: "Pamukkale",
    area: "Denizli, Türkiye",
    short: "Travertenlerin üzerindeki iç Ege sırtları.",
    overview: "Pamukkale ve Denizli sırtları iç Ege uçuş bölgesidir; hava kütlesi kuru ve çok rüzgarlı değilken termik çalışır.",
    flying: "Yazın iç kesimde CAPE çoğu zaman yüksektir. Kararsızlık uyarısı uçuşu kısaltma nedenidir, manzara bonusu değil.",
    season: "İlkbahar ve sonbahar; yaz ortası aşırı gelişir.",
  })),
  site("hasan-dagi", "TR", 38.126, 34.166, {
    name: "Hasan Dağı",
    area: "Aksaray, Turkey",
    short: "Central Anatolian volcano.",
    overview: "Hasan Dağı is a central Anatolian volcano, a high, dry mountain site flown in settled summer weather.",
    flying: "Altitude wind is stronger than the plain. Use this summit reference if that is the launch you mean.",
    season: "Summer, outside winter snow.",
  }, tr({
    name: "Hasan Dağı",
    area: "Aksaray, Türkiye",
    short: "İç Anadolu volkanı.",
    overview: "Hasan Dağı bir İç Anadolu volkanıdır; oturmuş yaz havasında uçulan yüksek ve kuru bir dağdır.",
    flying: "Yükseklikteki rüzgar ovadakinden güçlüdür. Kalkışın buysa bu zirve referansını kullan.",
    season: "Kış karı dışında yaz.",
  })),
  site("inonu", "TR", 39.815, 30.145, {
    name: "İnönü",
    area: "Eskişehir, Turkey",
    short: "Inland Eskişehir training and soaring area.",
    overview: "İnönü near Eskişehir is an inland Anatolian area used for training and local soaring on the steppe edge.",
    flying: "Open country means the 10 m wind is close to what you feel. Gust spread is still the turbulence clue.",
    season: "Spring through autumn.",
  }, tr({
    name: "İnönü",
    area: "Eskişehir, Türkiye",
    short: "Eskişehir iç kesiminde eğitim ve sırt alanı.",
    overview: "Eskişehir yakınındaki İnönü, bozkır kenarında eğitim ve yerel sırt uçuşu için kullanılan bir İç Anadolu alanıdır.",
    flying: "Açık arazide 10 m rüzgar, hissettiğine yakındır. Hamle farkı yine türbülans ipucudur.",
    season: "İlkbahardan sonbahara.",
  })),
  site("vidova-gora", "HR", 43.283, 16.622, {
    name: "Vidova gora",
    area: "Brač, Croatia",
    short: "The highest point of Brač, above Bol.",
    overview: "Vidova gora is the highest point of Brač, the classic Dalmatian launch above Bol when the sea breeze and the hill agree.",
    flying: "A strong maestral or jugo is not a thermal day. High sustained wind fails the filter on purpose.",
    season: "May to September; the sea breeze is strongest in summer.",
  }, hr({
    name: "Vidova gora",
    area: "Brač, Hrvatska",
    short: "Najviša točka Brača, iznad Bola.",
    overview: "Vidova gora je najviša točka Brača, klasično dalmatinsko uzletište iznad Bola kad se dnevni vjetar i brijeg slože.",
    flying: "Jak maestral ili jugo nisu termički dan. Jaka stalna brzina namjerno pada na filtru.",
    season: "Svibanj do rujan; dnevni vjetar je najjači ljeti.",
  })),
  site("biokovo", "HR", 43.333, 17.053, {
    name: "Biokovo",
    area: "Makarska, Croatia",
    short: "Coastal massif above the Makarska riviera.",
    overview: "Biokovo is the coastal massif above Makarska, a high Dalmatian site with a steep fall to the sea.",
    flying: "Bura days are a known hazard and often too strong and gusty for the conservative rules.",
    season: "Late spring through early autumn, avoiding strong bura.",
  }, hr({
    name: "Biokovo",
    area: "Makarska, Hrvatska",
    short: "Primorski masiv iznad Makarske rivijere.",
    overview: "Biokovo je primorski masiv iznad Makarske, visok dalmatinski teren sa strmim padom prema moru.",
    flying: "Dani s burom su poznata opasnost i često prejaki i udarni za oprezna pravila.",
    season: "Kasno proljeće do rane jeseni, uz izbjegavanje jake bure.",
  })),
  site("platak", "HR", 45.422, 14.468, {
    name: "Platak",
    area: "Rijeka, Croatia",
    short: "Ridge above Rijeka and the Kvarner bay.",
    overview: "Platak is the ridge above Rijeka, used for local soaring over the Kvarner when the wind is on the slope and not a full bura.",
    flying: "Bura through the Kvarner gap is stronger and gustier than a normal slope wind. Trust a high gust spread.",
    season: "Spring and autumn; winter bura is usually no-go.",
  }, hr({
    name: "Platak",
    area: "Rijeka, Hrvatska",
    short: "Greben iznad Rijeke i Kvarnera.",
    overview: "Platak je greben iznad Rijeke, za lokalno jedrenje nad Kvarnerom kad je vjetar na padini, a ne puna bura.",
    flying: "Bura kroz kvarnerska vrata jača je i udarnija od običnog padinskog vjetra. Vjeruj velikom rasponu udara.",
    season: "Proljeće i jesen; zimska bura je obično no-go.",
  })),
  site("ivanscica", "HR", 46.178, 16.123, {
    name: "Ivanščica",
    area: "Hrvatsko zagorje, Croatia",
    short: "Inland ridge in the Zagorje, north of Zagreb.",
    overview: "Ivanščica is an inland Zagorje ridge north of Zagreb, one of continental Croatia’s regular soaring hills.",
    flying: "Inland afternoons can build CAPE while the morning looked easy. Re-read the forecast before the second flight.",
    season: "April to October.",
  }, hr({
    name: "Ivanščica",
    area: "Hrvatsko zagorje",
    short: "Kopneni greben u Zagorju, sjeverno od Zagreba.",
    overview: "Ivanščica je zagorski greben sjeverno od Zagreba, jedan od redovitih kopnenih terena u Hrvatskoj.",
    flying: "Kopnena poslijepodneva mogu podići CAPE iako je jutro izgledalo lako. Ponovno pročitaj prognozu prije drugog leta.",
    season: "Travanj do listopad.",
  })),
  site("medvednica", "HR", 45.91, 15.95, {
    name: "Medvednica",
    area: "Zagreb, Croatia",
    short: "The mountain directly above Zagreb.",
    overview: "Medvednica is the mountain above Zagreb, a city-side soaring hill when the wind is on the southern or western slopes.",
    flying: "City-side wind and summit wind differ. This reference is the mountain, not the square below.",
    season: "Spring through autumn.",
  }, hr({
    name: "Medvednica",
    area: "Zagreb, Hrvatska",
    short: "Planina neposredno iznad Zagreba.",
    overview: "Medvednica je planina iznad Zagreba, gradski teren kad je vjetar na južnim ili zapadnim padinama.",
    flying: "Vjetar uz grad i vjetar na vrhu nisu isti. Ova referenca je planina, ne trg ispod nje.",
    season: "Od proljeća do jeseni.",
  })),
  site("hvar", "HR", 43.172, 16.441, {
    name: "Hvar",
    area: "Hvar island, Croatia",
    short: "Island ridges west of Brač.",
    overview: "Hvar’s ridges are the island option west of Brač, flown in a organised sea breeze along the Dalmatian channel.",
    flying: "Channel wind between Hvar and Brač can exceed either island’s local hope. Compare both reference points.",
    season: "May to September.",
  }, hr({
    name: "Hvar",
    area: "Otok Hvar, Hrvatska",
    short: "Otočni grebeni zapadno od Brača.",
    overview: "Grebeni Hvara su otočna opcija zapadno od Brača, u organiziranom dnevnom vjetru duž dalmatinskog kanala.",
    flying: "Vjetar u kanalu između Hvara i Brača može biti jači od nade na bilo kojem otoku. Usporedi obje referentne točke.",
    season: "Svibanj do rujan.",
  })),
  site("divcibare", "RS", 44.103, 19.991, {
    name: "Divčibare",
    area: "Maljen, Serbia",
    short: "Mountain plateau south-west of Belgrade.",
    overview: "Divčibare on Maljen is a mountain plateau south-west of Belgrade, one of Serbia’s most used soaring areas.",
    flying: "Plateau wind is exposed. Gust spread on an otherwise moderate day is the reason the status drops to marginal.",
    season: "May to September.",
  }, sr({
    name: "Divčibare",
    area: "Maljen, Srbija",
    short: "Planinski plato jugozapadno od Beograda.",
    overview: "Divčibare na Maljenu su planinski plato jugozapadno od Beograda, jedno od najkorišćenijih terena u Srbiji.",
    flying: "Vetar na platou je izložen. Raspon udara na inače umeren dan je razlog da status padne na graničan.",
    season: "Maj do septembar.",
  })),
  site("zlatibor", "RS", 43.726, 19.7, {
    name: "Zlatibor",
    area: "Western Serbia",
    short: "Broad western Serbian mountain.",
    overview: "Zlatibor is a broad western Serbian mountain, flown for local soaring and short cross-country in summer.",
    flying: "Several meadows are used. The reference point is the mountain, not every meadow the club might choose.",
    season: "Late spring through early autumn.",
  }, sr({
    name: "Zlatibor",
    area: "Zapadna Srbija",
    short: "Široka planina u zapadnoj Srbiji.",
    overview: "Zlatibor je široka planina zapadne Srbije, za lokalno jedrenje i kratke prelete leti.",
    flying: "Koristi se više livada. Referentna tačka je planina, ne svaka livada koju klub tog dana izabere.",
    season: "Kasno proleće do rane jeseni.",
  })),
  site("kopaonik", "RS", 43.285, 20.816, {
    name: "Kopaonik",
    area: "Central Serbia",
    short: "High central Serbian massif.",
    overview: "Kopaonik is a high central Serbian massif, a serious mountain site flown in settled summer weather.",
    flying: "Summit wind and valley wind are different samples. If you mean the top, use this coordinate.",
    season: "High summer; the resort is a ski hill in winter.",
  }, sr({
    name: "Kopaonik",
    area: "Centralna Srbija",
    short: "Visok masiv u središnjoj Srbiji.",
    overview: "Kopaonik je visok masiv središnje Srbije, ozbiljan planinski teren u ustaljenom letnjem vremenu.",
    flying: "Vetar na vrhu i vetar u dolini su različiti uzorci. Ako misliš na vrh, koristi ovu koordinatu.",
    season: "Sredina leta; zimi je skijalište.",
  })),
  site("fruska-gora", "RS", 45.161, 19.71, {
    name: "Fruška gora",
    area: "Syrmia, Serbia",
    short: "Low mountain above the Danube plain.",
    overview: "Fruška gora is the low mountain above the Danube plain, a northern Serbian soaring site close to Novi Sad.",
    flying: "Plain wind can be stronger than the wooded ridge suggests. Read the sustained speed at this coordinate.",
    season: "April to October.",
  }, sr({
    name: "Fruška gora",
    area: "Srem, Srbija",
    short: "Niska planina iznad dunavske ravnice.",
    overview: "Fruška gora je niska planina iznad dunavske ravnice, severni teren blizu Novog Sada.",
    flying: "Ravničarski vetar može biti jači nego što šumoviti greben deluje. Čitaj stalnu brzinu na ovoj koordinati.",
    season: "April do oktobar.",
  })),
  site("stara-planina", "RS", 43.37, 22.6, {
    name: "Stara planina",
    area: "Eastern Serbia",
    short: "Balkan ridge on the Bulgarian border.",
    overview: "Stara planina is the Balkan ridge on the Bulgarian border, an eastern Serbian mountain site.",
    flying: "Border ridges are exposed. Cloud and wind together fail the filters more often than a lowland hill.",
    season: "Summer months.",
  }, sr({
    name: "Stara planina",
    area: "Istočna Srbija",
    short: "Balkanski greben na bugarskoj granici.",
    overview: "Stara planina je balkanski greben na bugarskoj granici, istočni planinski teren.",
    flying: "Granični grebeni su izloženi. Oblak i vetar zajedno češće padaju na filterima nego nizijsko brdo.",
    season: "Letnji meseci.",
  })),
  site("rtanj", "RS", 43.776, 21.893, {
    name: "Rtanj",
    area: "Eastern Serbia",
    short: "Pyramidal mountain east of the Morava.",
    overview: "Rtanj is the pyramidal mountain east of the Morava, a distinctive eastern Serbian soaring site.",
    flying: "A pyramidal hill has a narrow working sector. Direction matters more than a single speed number.",
    season: "May to September.",
  }, sr({
    name: "Rtanj",
    area: "Istočna Srbija",
    short: "Piramidalna planina istočno od Morave.",
    overview: "Rtanj je piramidalna planina istočno od Morave, prepoznatljiv istočni teren.",
    flying: "Piramidalno brdo ima uzan radni sektor. Smer je važniji od jednog broja brzine.",
    season: "Maj do septembar.",
  })),
  site("llogara", "AL", 40.198, 19.591, {
    name: "Llogara",
    area: "Albanian Riviera",
    short: "Pass above the Ionian coast between Vlorë and Dhërmi.",
    overview: "Llogara Pass sits above the Ionian coast between Vlorë and Dhërmi, the best-known Albanian coastal flying area.",
    flying: "Sea breeze up the pass can be stronger than a town forecast. Use this pass coordinate if that is the launch.",
    season: "May to September.",
  }, sq({
    name: "Llogara",
    area: "Riviera shqiptare",
    short: "Qafa mbi bregun jonian mes Vlorës dhe Dhërmiut.",
    overview: "Qafa e Llogarasë qëndron mbi bregun jonian mes Vlorës dhe Dhërmiut, zona bregdetare më e njohur e fluturimit në Shqipëri.",
    flying: "Brezza e detit në qafë mund të jetë më e fortë se parashikimi i qytetit. Përdor këtë koordinatë nëse nisja është këtu.",
    season: "Maj deri në shtator.",
  })),
  site("dajti", "AL", 41.366, 19.924, {
    name: "Dajti",
    area: "Tirana, Albania",
    short: "The mountain directly above Tirana.",
    overview: "Dajti is the mountain above Tirana, a city-side soaring site when the wind is on the western slopes.",
    flying: "City heat and slope wind are different. This reference is the mountain grid.",
    season: "Spring through autumn.",
  }, sq({
    name: "Dajti",
    area: "Tiranë, Shqipëri",
    short: "Mali pikërisht mbi Tiranë.",
    overview: "Dajti është mali mbi Tiranë, terren anës qytetit kur era është në shpatet perëndimore.",
    flying: "Nxehtësia e qytetit dhe era e shpatit nuk janë e njëjta gjë. Kjo referencë është rrjeta e malit.",
    season: "Nga pranvera në vjeshtë.",
  })),
  site("valbona", "AL", 42.453, 19.887, {
    name: "Valbona",
    area: "Albanian Alps",
    short: "Valley in the Albanian Alps near the Montenegrin border.",
    overview: "Valbona is a valley in the Albanian Alps, a mountain site flown in settled summer weather, not as a training hill.",
    flying: "Valley wind and high-mountain cloud change quickly. A marginal score is a reason to stay in the valley.",
    season: "July and August, once snow has opened the valley.",
  }, sq({
    name: "Valbonë",
    area: "Alpet Shqiptare",
    short: "Luginë në Alpet Shqiptare, pranë kufirit malazez.",
    overview: "Valbona është luginë në Alpet Shqiptare, terren malor në mot të qëndrueshëm vere, jo kodër stërvitjeje.",
    flying: "Era e luginës dhe retë e malit ndryshojnë shpejt. Një pikë kufitare është arsye për të qëndruar në luginë.",
    season: "Korrik dhe gusht, pasi bora hap luginën.",
  })),
  site("theth", "AL", 42.395, 19.774, {
    name: "Theth",
    area: "Albanian Alps",
    short: "The neighbouring Albanian Alps valley to Valbona.",
    overview: "Theth is the neighbouring Albanian Alps valley, used when the wind suits this side of the range rather than Valbona.",
    flying: "Compare Theth and Valbona if you are choosing a valley. Neither forecast replaces a local look at the clouds.",
    season: "High summer.",
  }, sq({
    name: "Theth",
    area: "Alpet Shqiptare",
    short: "Lugina fqinje e Valbonës në Alpet Shqiptare.",
    overview: "Thethi është lugina fqinje, kur era i përshtatet kësaj ane të vargut dhe jo Valbonës.",
    flying: "Krahaso Thethin dhe Valbonën nëse po zgjedh luginë. Asnjë parashikim nuk zëvendëson vështrimin lokal të reve.",
    season: "Mesi i verës.",
  })),
  site("berat", "AL", 40.705, 19.952, {
    name: "Berat",
    area: "Central Albania",
    short: "Hills around the old town above the Osum.",
    overview: "Berat’s hills above the Osum are a central Albanian soaring area, lower and warmer than the Alps.",
    flying: "Summer afternoons inland can build CAPE. That caution is about thunderstorm risk, not about the historic town.",
    season: "Spring through early autumn.",
  }, sq({
    name: "Berat",
    area: "Shqipëria qendrore",
    short: "Kodra rreth qytetit të vjetër mbi Osum.",
    overview: "Kodrart e Beratit mbi Osum janë zonë qendrore, më të ulëta dhe më të ngrohta se Alpet.",
    flying: "Pasditet e verës në brendësi mund të rrisin CAPE. Ai kujdes është për rrezikun e stuhisë, jo për qytetin historik.",
    season: "Nga pranvera deri në fillim të vjeshtës.",
  })),
  site("dhermi", "AL", 40.152, 19.639, {
    name: "Dhërmi",
    area: "Albanian Riviera",
    short: "Ionian village below the Llogara road.",
    overview: "Dhërmi is the Ionian village below the Llogara road, a coastal reference when the pass itself is in cloud and the bay is the plan.",
    flying: "Pass and bay are different winds. If Llogara is no-go for cloud and Dhërmi is not, read both before you commit to the drive.",
    season: "May to September.",
  }, sq({
    name: "Dhërmi",
    area: "Riviera shqiptare",
    short: "Fshat jonian nën rrugën e Llogarasë.",
    overview: "Dhërmiu është fshati jonian nën rrugën e Llogarasë, referencë bregdetare kur qafa është në re dhe gjiri është plani.",
    flying: "Qafa dhe gjiri kanë erëra të ndryshme. Nëse Llogaraja është no-go për re dhe Dhërmiu jo, lexoji të dyja para rrugës.",
    season: "Maj deri në shtator.",
  })),
];
