import type { CopyLocale } from "../../content-locales";
import type { GuideCopyBundle } from "./guides";
import { fromPack, itPack, type Pack } from "./moreGuides";

function faq(items: readonly [string, string][]): Pack["faq"] {
  return items.map(([question, answer]) => ({ question, answer }));
}

function pack(overrides: Omit<Pack, "h"> & { h: Pack["h"] }): GuideCopyBundle {
  return fromPack({ ...itPack, ...overrides });
}

export const restGuides: Partial<Record<CopyLocale, GuideCopyBundle>> = {
  pt: pack({
    disclaimer:
      "Ajuda à decisão, não autorização de voo. Confirma o vento real na descolagem, o rotor, a convecção, as regras da zona e os teus limites.",
    updated: "Última atualização",
    aboutTitle: "Sobre o GlideWeather",
    aboutLead: "Consola de meteo hiperlocal para parapente: vento, rajadas, visibilidade e instabilidade antes de ires para a descolagem.",
    problem: "As apps gerais mostram números, raramente face a limites prudentes de parapente. O GlideWeather aplica as mesmas regras em cada pesquisa.",
    who: "Para pilotos que já conhecem o sítio, o espaço aéreo e os próprios limites. Não substitui o briefing nem a escola.",
    different: "Meteoblue se o servidor estiver configurado; caso contrário Open-Meteo. Daí saem pontuação, anel e motivos.",
    limits: "Estar na lista não significa que hoje se voa. O GlideWeather não autoriza a descolagem.",
    howTitle: "Como funciona o GlideWeather",
    howLead: "Das coordenadas ao veredito: local, previsão, sinais e janela de voo.",
    flow: "Escolhes um local por pesquisa, mapa, GPS ou preferência guardada. Cada hora é avaliada com as mesmas regras de vento, rajadas, amplitude, precipitação, visibilidade e CAPE.",
    output: "O painel mostra vento, rajadas, base estimada, visibilidade e seis horas. A gaveta acrescenta dias, CAPE e até quatro horas de luz que não são no-go.",
    data: "Previsão: Meteoblue com chave, senão Open-Meteo. Qualidade do ar e geocodificação: Open-Meteo.",
    weatherTitle: "Meteo parapente no GlideWeather",
    weatherLead: "Só os valores que o GlideWeather realmente carrega e como entram no veredito.",
    wind: "Vento demasiado fraco ou forte, rajadas em falta, rajadas altas e uma amplitude grande são sinais de risco.",
    visibility: "Abaixo de cerca de 10 km, cautela; abaixo de 5 km é no-go nas regras automáticas.",
    precip: "A quantidade e a probabilidade de chuva influenciam a pontuação.",
    instability: "CAPE acima dos limiares traz cautela ou no-go. A base no painel é estimada a partir da temperatura e da humidade.",
    air: "O AQI dos EUA e um UV alto podem tirar pontos. São sinais de apoio.",
    whenTitle: "Quando usar o GlideWeather",
    whenLead: "Momentos práticos: um anel verde não é autorização para descolar.",
    travel: "Compara vento e rajadas entre zonas. A ficha é contexto; a consola é a previsão no ponto de referência.",
    day: "Lê a pontuação e os motivos antes de montar e outra vez se mudarem nuvens ou vento.",
    monitor: "A resposta fica em cache cerca de 20 minutos.",
    windowTitle: "O que é uma janela de voo?",
    windowLead: "No GlideWeather são três coisas: a pontuação, a linha horária e as horas de luz ordenadas.",
    score: "Cada amostra começa em 100. Os limites duros forçam no-go. Cautela ou uma pontuação abaixo do limiar é marginal.",
    until: "A app percorre as horas do dia e vê quanto dura o mesmo estado.",
    ranked: "Até quatro horas que não são no-go. São horas soltas, não um bloco.",
    chart: "As cores marcam horas boas cujo vento não sobe mais de cerca de 3 km/h face à hora anterior.",
    faqTitle: "Perguntas frequentes de meteo parapente",
    faqLead: "Respostas alinhadas com o comportamento atual do GlideWeather.",
    faq: faq([
      ["O que é uma janela de voo de parapente?", "A pontuação 0–100, a duração do estado atual e até quatro horas de luz que não são no-go."],
      ["Como vejo o meteo antes de voar?", "Procura a zona ou abre um destino, lê vento, rajadas, visibilidade e motivos, e depois a previsão completa."],
      ["Que vento usa o GlideWeather?", "Limiares prudentes de vento a 10 m, rajadas e amplitude. São filtros de briefing, não limites legais universais."],
      ["Diz-me se é seguro?", "Não. Tu decides a descolagem, com conhecimento local e as regras em vigor."],
      ["Posso ver descolagens diferentes?", "Sim. Pesquisa no mundo, move o pin, usa o GPS ou as ligações. ?site= é estado da app e não é indexado."],
      ["Qual é a precisão da previsão?", "Depende do Meteoblue ou do Open-Meteo. Há cache curta. Abaixo de 30 % de previsibilidade Meteoblue aparece uma nota."],
      ["Que dados usa?", "Meteoblue se estiver configurado; senão a previsão Open-Meteo. Open-Meteo para qualidade do ar e pesquisa de lugares."],
    ]),
    homeTitle: "Meteo parapente num só sítio",
    homeA: "O GlideWeather transforma a previsão hiperlocal numa pontuação com motivos: vento, amplitude de rajadas, visibilidade, precipitação e instabilidade.",
    homeB: "Os guias explicam as regras. Os destinos abrem a consola sem dizer que hoje se voa.",
    hubTitle: "Destinos populares de parapente",
    hubLead: "Uma seleção para o briefing. Estar na lista não significa que hoje se voa.",
    hubUse: "Cada página descreve contexto, época e coordenadas de referência. «Abrir a previsão» carrega a consola.",
    h: {
      problem: "Que problema resolve",
      who: "Para quem é",
      different: "O que o distingue",
      limits: "O que não afirma",
      flow: "O fluxo",
      output: "O que vês",
      data: "Fontes",
      wind: "Vento e rajadas a 10 m",
      visibility: "Visibilidade",
      precip: "Precipitação",
      instability: "Instabilidade e nuvens",
      air: "Qualidade do ar e UV",
      travel: "Antes de sair",
      day: "No dia de voo",
      monitor: "Se mudar",
      score: "Pontuação",
      until: "Favorável até…",
      ranked: "Horas de luz ordenadas",
      chart: "As próximas seis horas",
      use: "Como usar a lista",
    },
  }),
  nl: packNl(),
  cs: packCs(),
  sk: packSk(),
  sl: packSl(),
  mt: packMt(),
  tr: packTr(),
  hr: packHr(),
  sr: packSr(),
  sq: packSq(),
};

function packNl(): GuideCopyBundle {
  return fromPack({
    ...itPack,
    disclaimer: "Beslishulp, geen vliegtoestemming. Controleer de echte wind op de start, rotor, convectie, gebiedsregels en je eigen limieten.",
    updated: "Laatst bijgewerkt",
    aboutTitle: "Over GlideWeather",
    aboutLead: "Hyperlokale weerconsole voor paragliding: wind, vlagen, zicht en instabiliteit vóór je naar de start rijdt.",
    problem: "Gewone weerapps tonen cijfers, zelden tegenover voorzichtige paraglidinggrenzen. GlideWeather past overal dezelfde regels toe.",
    who: "Voor piloten die terrein, luchtruim en eigen limieten al kennen. Het vervangt geen briefing en geen opleiding.",
    different: "Meteoblue als de server is ingesteld, anders Open-Meteo. Daaruit komen score, ring en redenen.",
    limits: "Op de lijst staan betekent niet dat het vandaag vliegbaar is. GlideWeather geeft geen startvrij.",
    howTitle: "Hoe GlideWeather werkt",
    howLead: "Van coördinaten naar een oordeel: plek, verwachting, signalen, vluchtvenster.",
    flow: "Je kiest een plek via zoeken, kaart, GPS of een opgeslagen standaard. Elk uur wordt met dezelfde regels voor wind, vlagen, spreiding, neerslag, zicht en CAPE beoordeeld.",
    output: "Het paneel toont wind, vlagen, geschatte basis, zicht en zes uur. De lade voegt dagen, CAPE en tot vier daglichturen toe die geen no-go zijn.",
    data: "Verwachting: Meteoblue met sleutel, anders Open-Meteo. Luchtkwaliteit en geocoding: Open-Meteo.",
    weatherTitle: "Paraglidingweer in GlideWeather",
    weatherLead: "Alleen waarden die GlideWeather echt laadt, en hoe ze in het oordeel komen.",
    wind: "Te weinig of te veel wind, ontbrekende vlagen, hoge vlagen en een grote spreiding zijn risicosignalen.",
    visibility: "Onder ongeveer 10 km voorzichtigheid; onder 5 km is no-go in de automatische regels.",
    precip: "Hoeveelheid en regenkans beïnvloeden de score.",
    instability: "CAPE boven de drempels geeft voorzichtigheid of no-go. De basis in het paneel is geschat uit temperatuur en vocht.",
    air: "Amerikaanse AQI en hoge UV kunnen punten aftrekken. Het zijn ondersteunende signalen.",
    whenTitle: "Wanneer je GlideWeather gebruikt",
    whenLead: "Praktische momenten: een groene ring is geen toestemming om te starten.",
    travel: "Vergelijk wind en vlagen tussen gebieden. De bestemmingspagina is context; de console is de verwachting op het referentiepunt.",
    day: "Lees score en redenen vóór het opbouwen en opnieuw als wolken of wind kantelen.",
    monitor: "Het antwoord blijft ongeveer 20 minuten in de cache.",
    windowTitle: "Wat is een vluchtvenster?",
    windowLead: "Bij GlideWeather zijn dat drie dingen: de score, de tijdregel en de gesorteerde daglichturen.",
    score: "Elk sample start op 100. Harde grenzen forceren no-go. Voorzichtigheid of een score onder de drempel is marginaal.",
    until: "De app loopt de uren van de dag af en ziet hoe lang dezelfde status blijft.",
    ranked: "Tot vier uren die geen no-go zijn. Losse uren, geen blok.",
    chart: "Kleuren markeren goede uren waarvan de wind niet meer dan ongeveer 3 km/h stijgt ten opzichte van het vorige uur.",
    faqTitle: "Veelgestelde vragen over paraglidingweer",
    faqLead: "Antwoorden die passen bij hoe GlideWeather vandaag werkt.",
    faq: faq([
      ["Wat is een paragliding-vluchtvenster?", "De score 0–100, hoe lang de huidige status aanhoudt, en tot vier daglichturen die geen no-go zijn."],
      ["Hoe check ik het weer vóór ik vlieg?", "Zoek het gebied of open een bestemming, lees wind, vlagen, zicht en redenen, daarna de volledige verwachting."],
      ["Welke wind gebruikt GlideWeather?", "Voorzichtige drempels voor 10 m-wind, vlagen en spreiding. Briefingfilters, geen universele wettelijke limieten."],
      ["Zegt GlideWeather of het veilig is?", "Nee. Jij beslist de start, met lokale kennis en geldende regels."],
      ["Kan ik verschillende starts bekijken?", "Ja. Zoek wereldwijd, versleep de pin, gebruik GPS of de links. ?site= is app-status en wordt niet geïndexeerd."],
      ["Hoe nauwkeurig is de verwachting?", "Dat hangt van Meteoblue of Open-Meteo af. Antwoorden worden kort gecachet. Onder 30 % Meteoblue-voorspelbaarheid verschijnt een notitie."],
      ["Welke data worden gebruikt?", "Meteoblue indien geconfigureerd, anders de Open-Meteo-verwachting; Open-Meteo voor luchtkwaliteit en plaatszoeken."],
    ]),
    homeTitle: "Paraglidingweer op één plek",
    homeA: "GlideWeather maakt van de hyperlokale verwachting een score met redenen: wind, vlaagspreiding, zicht, neerslag en instabiliteit.",
    homeB: "De gidsen leggen de regels uit. De bestemmingen openen de console, zonder te zeggen dat het vandaag vliegbaar is.",
    hubTitle: "Populaire paraglidingbestemmingen",
    hubLead: "Een selectie voor de briefing. Op de lijst staan betekent niet dat het vandaag vliegbaar is.",
    hubUse: "Elke pagina noemt context, seizoen en referentiecoördinaten. «Verwachting openen» laadt de console.",
    h: {
      problem: "Welk probleem het oplost",
      who: "Voor wie",
      different: "Wat anders is",
      limits: "Wat het niet beweert",
      flow: "De stroom",
      output: "Wat je ziet",
      data: "Bronnen",
      wind: "Wind en vlagen op 10 m",
      visibility: "Zicht",
      precip: "Neerslag",
      instability: "Instabiliteit en wolken",
      air: "Luchtkwaliteit en UV",
      travel: "Vóór je rijdt",
      day: "Op de vliegdag",
      monitor: "Als het verandert",
      score: "Score",
      until: "Gunstig tot…",
      ranked: "Gesorteerde daglichturen",
      chart: "De komende zes uur",
      use: "Zo gebruik je de lijst",
    },
  });
}

function packCs(): GuideCopyBundle {
  return fromPack({
    ...itPack,
    disclaimer: "Pomůcka k rozhodnutí, ne povolení letu. Ověř skutečný vítr na startu, rotor, konvekci, pravidla terénu a vlastní limity.",
    updated: "Naposledy aktualizováno",
    aboutTitle: "O GlideWeather",
    aboutLead: "Hyperlokální konzole počasí pro paragliding: vítr, nárazy, dohlednost a nestabilita před cestou na start.",
    problem: "Běžné aplikace ukazují čísla, málokdy vůči opatrným limitům paraglidingu. GlideWeather používá všude stejná pravidla.",
    who: "Pro piloty, kteří už znají terén, vzdušný prostor a vlastní limity. Nenahrazuje briefing ani školu.",
    different: "Meteoblue, je-li server nastaven, jinak Open-Meteo. Z toho je skóre, kruh a důvody.",
    limits: "Být na seznamu neznamená, že se dnes létá. GlideWeather start nepovoluje.",
    howTitle: "Jak GlideWeather funguje",
    howLead: "Od souřadnic k verdiktu: místo, předpověď, signály, letové okno.",
    flow: "Místo vybereš hledáním, mapou, GPS nebo uloženou předvolbou. Každá hodina se hodnotí stejnými pravidly větru, nárazů, rozptylu, srážek, dohlednosti a CAPE.",
    output: "Panel ukáže vítr, nárazy, odhadovanou základnu, dohlednost a šest hodin. Šuplík přidá dny, CAPE a až čtyři denní hodiny, které nejsou no-go.",
    data: "Předpověď: Meteoblue s klíčem, jinak Open-Meteo. Kvalita vzduchu a geokódování: Open-Meteo.",
    weatherTitle: "Počasí pro paragliding v GlideWeather",
    weatherLead: "Jen hodnoty, které GlideWeather opravdu načte, a jak vstupují do verdiktu.",
    wind: "Příliš slabý nebo silný vítr, chybějící nárazy, vysoké nárazy a velký rozptyl jsou rizikové signály.",
    visibility: "Pod zhruba 10 km opatrnost; pod 5 km je v automatických pravidlech no-go.",
    precip: "Množství a pravděpodobnost deště ovlivňují skóre.",
    instability: "CAPE nad prahy znamená opatrnost nebo no-go. Základna na panelu je odhad z teploty a vlhkosti.",
    air: "Americké AQI a vysoké UV mohou ubrat body. Jsou to doprovodné signály.",
    whenTitle: "Kdy GlideWeather použít",
    whenLead: "Praktické chvíle: zelený kruh není povolení ke startu.",
    travel: "Porovnej vítr a nárazy mezi terény. Stránka lokality je kontext; konzole je předpověď v referenčním bodě.",
    day: "Přečti skóre a důvody před stavěním a znovu, když se změní mraky nebo vítr.",
    monitor: "Odpověď zůstane v mezipaměti asi 20 minut.",
    windowTitle: "Co je letové okno?",
    windowLead: "V GlideWeather jsou to tři věci: skóre, časový řádek a seřazené denní hodiny.",
    score: "Každý vzorek začíná na 100. Tvrdé limity vynutí no-go. Opatrnost nebo skóre pod prahem je hraniční.",
    until: "Aplikace projde hodiny dne a sleduje, jak dlouho stejný stav vydrží.",
    ranked: "Až čtyři hodiny, které nejsou no-go. Jsou to jednotlivé hodiny, ne blok.",
    chart: "Barvy značí dobré hodiny, jejichž vítr nestoupne o víc než asi 3 km/h proti předchozí hodině.",
    faqTitle: "Časté otázky k počasí pro paragliding",
    faqLead: "Odpovědi odpovídající tomu, jak se GlideWeather dnes chová.",
    faq: faq([
      ["Co je letové okno v paraglidingu?", "Skóre 0–100, jak dlouho trvá aktuální stav a až čtyři denní hodiny, které nejsou no-go."],
      ["Jak zkontroluju počasí před letem?", "Vyhledej terén nebo otevři lokalitu, přečti vítr, nárazy, dohlednost a důvody, pak celou předpověď."],
      ["Jaký vítr GlideWeather používá?", "Opatrné prahy větru v 10 m, nárazů a rozptylu. Jsou to filtry pro briefing, ne univerzální zákonné limity."],
      ["Řekne mi, jestli je to bezpečné?", "Ne. O startu rozhoduješ ty, se znalostí terénu a platnými pravidly."],
      ["Můžu porovnat různé starty?", "Ano. Hledej po světě, posuň špendlík, použij GPS nebo odkazy. ?site= je stav aplikace a neindexuje se."],
      ["Jak přesná je předpověď?", "Záleží na Meteoblue nebo Open-Meteo. Odpovědi se krátce cachují. Pod 30 % předvídatelnosti Meteoblue se objeví poznámka."],
      ["Jaká data se používají?", "Meteoblue, je-li nastaveno, jinak předpověď Open-Meteo; Open-Meteo pro kvalitu vzduchu a hledání míst."],
    ]),
    homeTitle: "Počasí pro paragliding na jednom místě",
    homeA: "GlideWeather udělá z hyperlokální předpovědi skóre s důvody: vítr, rozptyl nárazů, dohlednost, srážky a nestabilita.",
    homeB: "Průvodci vysvětlují pravidla. Lokality otevírají konzoli a netvrdí, že se dnes létá.",
    hubTitle: "Oblíbené paraglidingové lokality",
    hubLead: "Výběr pro briefing. Záznam neznamená, že se dnes létá.",
    hubUse: "Každá stránka popisuje kontext, sezónu a referenční souřadnice. «Otevřít předpověď» načte konzoli.",
    h: {
      problem: "Jaký problém řeší",
      who: "Pro koho",
      different: "V čem je jiné",
      limits: "Co netvrdí",
      flow: "Postup",
      output: "Co uvidíš",
      data: "Zdroje",
      wind: "Vítr a nárazy v 10 m",
      visibility: "Dohlednost",
      precip: "Srážky",
      instability: "Nestabilita a oblaka",
      air: "Kvalita vzduchu a UV",
      travel: "Před cestou",
      day: "V letový den",
      monitor: "Když se to mění",
      score: "Skóre",
      until: "Příznivé do…",
      ranked: "Seřazené denní hodiny",
      chart: "Příštích šest hodin",
      use: "Jak seznam použít",
    },
  });
}

function packSk(): GuideCopyBundle {
  return fromPack({
    ...itPack,
    disclaimer: "Pomôcka na rozhodnutie, nie povolenie letu. Over skutočný vietor na štarte, rotor, konvekciu, pravidlá terénu a vlastné limity.",
    updated: "Naposledy aktualizované",
    aboutTitle: "O GlideWeather",
    aboutLead: "Hyperlokálna konzola počasia pre paragliding: vietor, nárazy, dohľadnosť a nestabilita pred cestou na štart.",
    problem: "Bežné aplikácie ukazujú čísla, málokedy voči opatrným limitom paraglidingu. GlideWeather používa všade rovnaké pravidlá.",
    who: "Pre pilotov, ktorí už poznajú terén, vzdušný priestor a vlastné limity. Nenahrádza brífing ani školu.",
    different: "Meteoblue, ak je server nastavený, inak Open-Meteo. Z toho je skóre, kruh a dôvody.",
    limits: "Byť na zozname neznamená, že sa dnes lieta. GlideWeather štart nepovoľuje.",
    howTitle: "Ako GlideWeather funguje",
    howLead: "Od súradníc k verdiktu: miesto, predpoveď, signály, letové okno.",
    flow: "Miesto vyberieš hľadaním, mapou, GPS alebo uloženou predvoľbou. Každá hodina sa hodnotí rovnakými pravidlami vetra, nárazov, rozptylu, zrážok, dohľadnosti a CAPE.",
    output: "Panel ukáže vietor, nárazy, odhadovanú základňu, dohľadnosť a šesť hodín. Zásuvka pridá dni, CAPE a až štyri denné hodiny, ktoré nie sú no-go.",
    data: "Predpoveď: Meteoblue s kľúčom, inak Open-Meteo. Kvalita vzduchu a geokódovanie: Open-Meteo.",
    weatherTitle: "Počasie pre paragliding v GlideWeather",
    weatherLead: "Len hodnoty, ktoré GlideWeather naozaj načíta, a ako vstupujú do verdiktu.",
    wind: "Príliš slabý alebo silný vietor, chýbajúce nárazy, vysoké nárazy a veľký rozptyl sú rizikové signály.",
    visibility: "Pod zhruba 10 km opatrnosť; pod 5 km je v automatických pravidlách no-go.",
    precip: "Množstvo a pravdepodobnosť dažďa ovplyvňujú skóre.",
    instability: "CAPE nad prahmi znamená opatrnosť alebo no-go. Základňa na paneli je odhad z teploty a vlhkosti.",
    air: "Americké AQI a vysoké UV môžu ubrať body. Sú to sprievodné signály.",
    whenTitle: "Kedy GlideWeather použiť",
    whenLead: "Praktické chvíle: zelený kruh nie je povolenie na štart.",
    travel: "Porovnaj vietor a nárazy medzi terénmi. Stránka lokality je kontext; konzola je predpoveď v referenčnom bode.",
    day: "Prečítaj skóre a dôvody pred stavaním a znova, keď sa zmenia mraky alebo vietor.",
    monitor: "Odpoveď zostane v medzipamäti asi 20 minút.",
    windowTitle: "Čo je letové okno?",
    windowLead: "V GlideWeather sú to tri veci: skóre, časový riadok a zoradené denné hodiny.",
    score: "Každá vzorka začína na 100. Tvrdé limity vynútia no-go. Opatrnosť alebo skóre pod prahom je hraničné.",
    until: "Aplikácia prejde hodiny dňa a sleduje, ako dlho rovnaký stav vydrží.",
    ranked: "Až štyri hodiny, ktoré nie sú no-go. Sú to jednotlivé hodiny, nie blok.",
    chart: "Farby značia dobré hodiny, ktorých vietor nestúpne o viac než asi 3 km/h oproti predchádzajúcej hodine.",
    faqTitle: "Časté otázky k počasiu pre paragliding",
    faqLead: "Odpovede zodpovedajúce tomu, ako sa GlideWeather dnes správa.",
    faq: faq([
      ["Čo je letové okno v paraglidingu?", "Skóre 0–100, ako dlho trvá aktuálny stav a až štyri denné hodiny, ktoré nie sú no-go."],
      ["Ako skontrolujem počasie pred letom?", "Vyhľadaj terén alebo otvor lokalitu, prečítaj vietor, nárazy, dohľadnosť a dôvody, potom celú predpoveď."],
      ["Aký vietor GlideWeather používa?", "Opatrné prahy vetra v 10 m, nárazov a rozptylu. Sú to filtre na brífing, nie univerzálne zákonné limity."],
      ["Povie mi, či je to bezpečné?", "Nie. O štarte rozhoduješ ty, so znalosťou terénu a platnými pravidlami."],
      ["Môžem porovnať rôzne štarty?", "Áno. Hľadaj po svete, posuň špendlík, použi GPS alebo odkazy. ?site= je stav aplikácie a neindexuje sa."],
      ["Aká presná je predpoveď?", "Závisí od Meteoblue alebo Open-Meteo. Odpovede sa krátko cachujú. Pod 30 % predvídateľnosti Meteoblue sa objaví poznámka."],
      ["Aké dáta sa používajú?", "Meteoblue, ak je nastavené, inak predpoveď Open-Meteo; Open-Meteo pre kvalitu vzduchu a hľadanie miest."],
    ]),
    homeTitle: "Počasie pre paragliding na jednom mieste",
    homeA: "GlideWeather urobí z hyperlokálnej predpovede skóre s dôvodmi: vietor, rozptyl nárazov, dohľadnosť, zrážky a nestabilita.",
    homeB: "Sprievodcovia vysvetľujú pravidlá. Lokality otvárajú konzolu a netvrdia, že sa dnes lieta.",
    hubTitle: "Obľúbené paraglidingové lokality",
    hubLead: "Výber na brífing. Záznam neznamená, že sa dnes lieta.",
    hubUse: "Každá stránka opisuje kontext, sezónu a referenčné súradnice. «Otvoriť predpoveď» načíta konzolu.",
    h: {
      problem: "Aký problém rieši",
      who: "Pre koho",
      different: "V čom je iné",
      limits: "Čo netvrdí",
      flow: "Postup",
      output: "Čo uvidíš",
      data: "Zdroje",
      wind: "Vietor a nárazy v 10 m",
      visibility: "Dohľadnosť",
      precip: "Zrážky",
      instability: "Nestabilita a oblaky",
      air: "Kvalita vzduchu a UV",
      travel: "Pred cestou",
      day: "V letový deň",
      monitor: "Keď sa to mení",
      score: "Skóre",
      until: "Priaznivé do…",
      ranked: "Zoradené denné hodiny",
      chart: "Najbližších šesť hodín",
      use: "Ako zoznam použiť",
    },
  });
}

function packSl(): GuideCopyBundle {
  return fromPack({
    ...itPack,
    disclaimer: "Pomoč pri odločitvi, ne dovoljenje za let. Preveri pravi veter na vzletišču, rotor, konvekcijo, pravila območja in lastne meje.",
    updated: "Nazadnje posodobljeno",
    aboutTitle: "O GlideWeather",
    aboutLead: "Hiperlokalna vremenska konzola za jadralno padalstvo: veter, sunki, vidljivost in nestabilnost, preden greš na vzletišče.",
    problem: "Navadne vremenske aplikacije kažejo številke, redko glede na previdne meje jadralnega padalstva. GlideWeather povsod uporablja ista pravila.",
    who: "Za pilote, ki teren, zračni prostor in lastne meje že poznajo. Ne nadomešča brifinga in šole.",
    different: "Meteoblue, če je strežnik nastavljen, sicer Open-Meteo. Iz tega sta ocena, obroč in razlogi.",
    limits: "Biti na seznamu ne pomeni, da se danes leta. GlideWeather vzleta ne dovoli.",
    howTitle: "Kako deluje GlideWeather",
    howLead: "Od koordinat do razsodbe: kraj, napoved, signali, letalno okno.",
    flow: "Kraj izbereš z iskanjem, zemljevidom, GPS ali shranjeno nastavitvijo. Vsaka ura se oceni z istimi pravili za veter, sunke, razpon, padavine, vidljivost in CAPE.",
    output: "Plošča pokaže veter, sunke, ocenjeno bazo, vidljivost in šest ur. Predal doda dneve, CAPE in do štiri dnevne ure, ki niso no-go.",
    data: "Napoved: Meteoblue s ključem, sicer Open-Meteo. Kakovost zraka in geokodiranje: Open-Meteo.",
    weatherTitle: "Vreme za jadralno padalstvo v GlideWeather",
    weatherLead: "Samo vrednosti, ki jih GlideWeather res naloži, in kako vstopijo v razsodbo.",
    wind: "Prešibek ali premočan veter, manjkajoči sunki, visoki sunki in velik razpon so tvegani signali.",
    visibility: "Pod približno 10 km previdnost; pod 5 km je v samodejnih pravilih no-go.",
    precip: "Količina in verjetnost dežja vplivata na oceno.",
    instability: "CAPE nad pragi pomeni previdnost ali no-go. Baza na plošči je ocena iz temperature in vlage.",
    air: "Ameriški AQI in visok UV lahko odštejeta točke. To so podporni signali.",
    whenTitle: "Kdaj uporabiti GlideWeather",
    whenLead: "Praktični trenutki: zelen obroč ni dovoljenje za vzlet.",
    travel: "Primerjaj veter in sunke med območji. Stran destinacije je kontekst; konzola je napoved v referenčni točki.",
    day: "Preberi oceno in razloge pred pripravo in znova, če se spremenijo oblaki ali veter.",
    monitor: "Odgovor ostane v predpomnilniku približno 20 minut.",
    windowTitle: "Kaj je letalno okno?",
    windowLead: "V GlideWeather so to tri stvari: ocena, časovna vrstica in razvrščene dnevne ure.",
    score: "Vsak vzorec se začne pri 100. Trde meje vsilijo no-go. Previdnost ali ocena pod pragom je mejna.",
    until: "Aplikacija gre skozi ure dneva in vidi, kako dolgo traja isto stanje.",
    ranked: "Do štiri ure, ki niso no-go. Posamezne ure, ne blok.",
    chart: "Barve označijo dobre ure, katerih veter ne naraste za več kot približno 3 km/h glede na prejšnjo uro.",
    faqTitle: "Pogosta vprašanja o vremenu za jadralno padalstvo",
    faqLead: "Odgovori, usklajeni s tem, kako se GlideWeather danes obnaša.",
    faq: faq([
      ["Kaj je letalno okno v jadralnem padalstvu?", "Ocena 0–100, kako dolgo traja trenutno stanje in do štiri dnevne ure, ki niso no-go."],
      ["Kako preverim vreme pred letenjem?", "Poišči območje ali odpri destinacijo, preberi veter, sunke, vidljivost in razloge, nato celotno napoved."],
      ["Kateri veter uporablja GlideWeather?", "Previdni pragi vetra na 10 m, sunkov in razpona. To so filtri za brifing, ne splošne zakonske meje."],
      ["Mi pove, ali je varno?", "Ne. O vzletu odločiš ti, z znanjem terena in veljavnimi pravili."],
      ["Lahko primerjam različna vzletišča?", "Da. Išči po svetu, premakni žebljiček, uporabi GPS ali povezave. ?site= je stanje aplikacije in se ne indeksira."],
      ["Kako natančna je napoved?", "Odvisno od Meteoblue ali Open-Meteo. Odgovori se kratko shranijo. Pod 30 % predvidljivosti Meteoblue se pojavi opomba."],
      ["Katere podatke uporablja?", "Meteoblue, če je nastavljen, sicer napoved Open-Meteo; Open-Meteo za kakovost zraka in iskanje krajev."],
    ]),
    homeTitle: "Vreme za jadralno padalstvo na enem mestu",
    homeA: "GlideWeather iz hiperlokalne napovedi naredi oceno z razlogi: veter, razpon sunkov, vidljivost, padavine in nestabilnost.",
    homeB: "Vodniki razložijo pravila. Destinacije odprejo konzolo in ne trdijo, da se danes leta.",
    hubTitle: "Priljubljene destinacije za jadralno padalstvo",
    hubLead: "Izbor za brifing. Vnos ne pomeni, da se danes leta.",
    hubUse: "Vsaka stran opiše kontekst, sezono in referenčne koordinate. «Odpri napoved» naloži konzolo.",
    h: {
      problem: "Katero težavo rešuje",
      who: "Za koga",
      different: "V čem je drugačen",
      limits: "Česa ne trdi",
      flow: "Potek",
      output: "Kaj vidiš",
      data: "Viri",
      wind: "Veter in sunki na 10 m",
      visibility: "Vidljivost",
      precip: "Padavine",
      instability: "Nestabilnost in oblaki",
      air: "Kakovost zraka in UV",
      travel: "Pred potjo",
      day: "Na letalni dan",
      monitor: "Ko se spremeni",
      score: "Ocena",
      until: "Ugodno do…",
      ranked: "Razvrščene dnevne ure",
      chart: "Naslednjih šest ur",
      use: "Kako uporabiti seznam",
    },
  });
}

function packMt(): GuideCopyBundle {
  return fromPack({
    ...itPack,
    disclaimer: "Għajnuna għad-deċiżjoni, mhux awtorizzazzjoni tat-titjira. Ikkonferma r-riħ veru fit-tlugħ, ir-rotor, il-konvezzjoni, ir-regoli taż-żona u l-limiti tiegħek.",
    updated: "Aġġornat l-aħħar",
    aboutTitle: "Dwar GlideWeather",
    aboutLead: "Konsola tat-temp iperlokali għall-paragliding: riħ, buffuri, viżibilità u instabbiltà qabel tmur għat-tlugħ.",
    problem: "L-apps ġenerali juru numri, rari kontra limiti prudenti tal-paragliding. GlideWeather juża l-istess regoli kullimkien.",
    who: "Għal piloti li diġà jafu t-terren, l-ispazju tal-ajru u l-limiti tagħhom. Ma jissostitwixxix briefing jew skola.",
    different: "Meteoblue jekk is-server ikun konfigurat, inkella Open-Meteo. Minn hemm joħorġu punteġġ, ċirku u raġunijiet.",
    limits: "Li tkun fil-lista ma jfissirx li llum tista’ ttir. GlideWeather ma jawtorizzax it-tlugħ.",
    howTitle: "Kif jaħdem GlideWeather",
    howLead: "Mill-koordinati għall-verdett: post, tbassir, sinjali, tieqa tat-titjira.",
    flow: "Tagħżel post bit-tfittxija, il-mappa, il-GPS jew preferenza ssejvjata. Kull siegħa tiġi vvalutata bl-istess regoli ta’ riħ, buffuri, firxa, xita, viżibilità u CAPE.",
    output: "Il-pannell juri riħ, buffuri, bażi stmata, viżibilità u sitt sigħat. Il-kexxun iżid jiem, CAPE u sa erba’ sigħat ta’ dawl li mhumiex no-go.",
    data: "Tbassir: Meteoblue b’ċavetta, inkella Open-Meteo. Kwalità tal-arja u geocoding: Open-Meteo.",
    weatherTitle: "Temp għall-paragliding f’GlideWeather",
    weatherLead: "Biss il-valuri li GlideWeather tassew jgħabbi, u kif jidħlu fil-verdett.",
    wind: "Riħ dgħajjef wisq jew qawwi wisq, buffuri nieqsa, buffuri għoljin u firxa kbira huma sinjali ta’ riskju.",
    visibility: "Taħt madwar 10 km kawtela; taħt 5 km huwa no-go fir-regoli awtomatiċi.",
    precip: "L-ammont u l-probabbiltà tax-xita jinfluwenzaw il-punteġġ.",
    instability: "CAPE fuq il-limiti jġib kawtela jew no-go. Il-bażi fil-pannell hija stima mit-temperatura u l-umdità.",
    air: "L-AQI Amerikan u UV għoli jistgħu ineħħu punti. Huma sinjali ta’ appoġġ.",
    whenTitle: "Meta tuża GlideWeather",
    whenLead: "Mumenti prattiċi: ċirku aħdar mhux permess biex titlaq.",
    travel: "Qabbel ir-riħ u l-buffuri bejn iż-żoni. Il-paġna tad-destinazzjoni hija kuntest; il-konsola hija t-tbassir fil-punt ta’ referenza.",
    day: "Aqra l-punteġġ u r-raġunijiet qabel tħejji u mill-ġdid jekk jinbidlu s-sħab jew ir-riħ.",
    monitor: "It-tweġiba tibqa’ fil-cache madwar 20 minuta.",
    windowTitle: "X’inhi tieqa tat-titjira?",
    windowLead: "F’GlideWeather huma tliet affarijiet: il-punteġġ, il-linja tal-ħin u s-sigħat tad-dawl magħżula.",
    score: "Kull kampjun jibda minn 100. Limiti iebsin jisforzaw no-go. Kawtela jew punteġġ taħt il-limitu huwa marġinali.",
    until: "L-app tgħaddi mis-sigħat tal-ġurnata u tara kemm idum l-istess stat.",
    ranked: "Sa erba’ sigħat li mhumiex no-go. Sigħat separati, mhux blokk.",
    chart: "Il-kuluri jimmarkaw sigħat tajbin li r-riħ tagħhom ma jitlax aktar minn madwar 3 km/h mis-siegħa ta’ qabel.",
    faqTitle: "Mistoqsijiet dwar it-temp għall-paragliding",
    faqLead: "Tweġibiet skont kif GlideWeather iġib ruħu llum.",
    faq: faq([
      ["X’inhi tieqa tat-titjira fil-paragliding?", "Il-punteġġ 0–100, kemm idum l-istat attwali, u sa erba’ sigħat ta’ dawl li mhumiex no-go."],
      ["Kif niċċekkja t-temp qabel nitir?", "Fittex iż-żona jew iftaħ destinazzjoni, aqra r-riħ, il-buffuri, il-viżibilità u r-raġunijiet, imbagħad it-tbassir sħiħ."],
      ["Liema riħ juża GlideWeather?", "Limiti prudenti tar-riħ f’10 m, buffuri u firxa. Huma filtri ta’ briefing, mhux limiti legali universali."],
      ["Jgħidli jekk huwiex sigur?", "Le. Int tiddeċiedi t-tlugħ, bl-għarfien lokali u r-regoli fis-seħħ."],
      ["Nista’ nqabbel tlugħ differenti?", "Iva. Fittex mad-dinja, ċaqlaq il-pin, uża l-GPS jew il-links. ?site= huwa stat tal-app u ma jiġix indiċjat."],
      ["Kemm hu preċiż it-tbassir?", "Jiddependi minn Meteoblue jew Open-Meteo. It-tweġibiet jinħażnu fil-qosor. Taħt 30 % prevedibbiltà ta’ Meteoblue tidher nota."],
      ["Liema data juża?", "Meteoblue jekk ikun konfigurat, inkella t-tbassir ta’ Open-Meteo; Open-Meteo għall-kwalità tal-arja u t-tfittxija tal-postijiet."],
    ]),
    homeTitle: "Temp għall-paragliding f’post wieħed",
    homeA: "GlideWeather jibdel it-tbassir iperlokali f’punteġġ b’raġunijiet: riħ, firxa tal-buffuri, viżibilità, xita u instabbiltà.",
    homeB: "Il-gwidi jispjegaw ir-regoli. Id-destinazzjonijiet jiftħu l-konsola mingħajr ma jgħidu li llum tista’ ttir.",
    hubTitle: "Destinazzjonijiet popolari tal-paragliding",
    hubLead: "Għażla għall-briefing. Li tkun fil-lista ma jfissirx li llum tista’ ttir.",
    hubUse: "Kull paġna tiddeskrivi l-kuntest, l-istaġun u l-koordinati ta’ referenza. «Iftaħ it-tbassir» jgħabbi l-konsola.",
    h: {
      problem: "Liema problema jsolvi",
      who: "Għal min",
      different: "X’hemm differenti",
      limits: "X’ma jaffermawx",
      flow: "Il-fluss",
      output: "X’tara",
      data: "Sorsi",
      wind: "Riħ u buffuri f’10 m",
      visibility: "Viżibilità",
      precip: "Xita",
      instability: "Instabbiltà u sħab",
      air: "Kwalità tal-arja u UV",
      travel: "Qabel titlaq",
      day: "Fil-ġurnata tat-titjira",
      monitor: "Jekk jinbidel",
      score: "Punteġġ",
      until: "Favorevoli sa…",
      ranked: "Sigħat ta’ dawl magħżula",
      chart: "Is-sitt sigħat li ġejjin",
      use: "Kif tuża l-lista",
    },
  });
}

function packTr(): GuideCopyBundle {
  return fromPack({
    ...itPack,
    disclaimer: "Karar desteği, uçuş izni değil. Kalkıştaki gerçek rüzgarı, rotoru, konveksiyonu, alan kurallarını ve kendi limitlerini doğrula.",
    updated: "Son güncelleme",
    aboutTitle: "GlideWeather hakkında",
    aboutLead: "Yamaç paraşütü için hiper yerel hava konsolu: kalkışa gitmeden rüzgar, hamle, görüş ve kararsızlık.",
    problem: "Genel hava uygulamaları sayıları gösterir, temkinli yamaç paraşütü sınırlarına göre nadiren. GlideWeather her aramada aynı kuralları kullanır.",
    who: "Araziyi, hava sahasını ve kendi limitlerini bilen pilotlar için. Brifingi ve eğitimi yerine koymaz.",
    different: "Sunucu ayarlıysa Meteoblue, değilse Open-Meteo. Bundan puan, halka ve gerekçeler çıkar.",
    limits: "Listede olmak bugün uçulur demek değildir. GlideWeather kalkışa izin vermez.",
    howTitle: "GlideWeather nasıl çalışır",
    howLead: "Koordinattan karara: yer, tahmin, sinyaller, uçuş penceresi.",
    flow: "Yeri arama, harita, GPS veya kayıtlı tercihle seçersin. Her saat rüzgar, hamle, fark, yağış, görüş ve CAPE için aynı kurallarla değerlendirilir.",
    output: "Panel rüzgar, hamle, tahmini taban, görüş ve altı saati gösterir. Çekmece günler, CAPE ve no-go olmayan en fazla dört gündüz saati ekler.",
    data: "Tahmin: anahtarla Meteoblue, yoksa Open-Meteo. Hava kalitesi ve coğrafi kodlama: Open-Meteo.",
    weatherTitle: "GlideWeather’da yamaç paraşütü havası",
    weatherLead: "Yalnızca GlideWeather’ın gerçekten yüklediği değerler ve karara nasıl girdikleri.",
    wind: "Çok zayıf veya güçlü rüzgar, eksik hamle, yüksek hamle ve büyük fark risk işaretidir.",
    visibility: "Yaklaşık 10 km altında dikkat; 5 km altında otomatik kurallarda no-go’dur.",
    precip: "Miktar ve yağmur olasılığı puanı etkiler.",
    instability: "Eşik üstü CAPE dikkat veya no-go getirir. Paneldeki taban sıcaklık ve nemden tahmin edilir.",
    air: "ABD AQI ve yüksek UV puan düşürebilir. Destekleyici işaretlerdir.",
    whenTitle: "GlideWeather ne zaman kullanılır",
    whenLead: "Pratik anlar: yeşil halka kalkış izni değildir.",
    travel: "Bölgeler arasında rüzgar ve hamleyi karşılaştır. Sayfa bağlamdır; konsol referans noktasındaki tahmindir.",
    day: "Kurmadan önce puanı ve gerekçeleri oku, bulut veya rüzgar değişirse yeniden oku.",
    monitor: "Yanıt yaklaşık 20 dakika önbellekte kalır.",
    windowTitle: "Uçuş penceresi nedir?",
    windowLead: "GlideWeather’da üç şeydir: puan, zaman satırı ve sıralanmış gündüz saatleri.",
    score: "Her örnek 100’den başlar. Sert sınırlar no-go zorlar. Dikkat veya eşiğin altı sınırdadır.",
    until: "Uygulama günün saatlerini tarar ve aynı durumun ne kadar sürdüğünü görür.",
    ranked: "No-go olmayan en fazla dört saat. Ayrı saatlerdir, blok değil.",
    chart: "Renkler, rüzgarı bir önceki saate göre yaklaşık 3 km/s’den fazla artmayan iyi saatleri işaretler.",
    faqTitle: "Yamaç paraşütü hava durumu SSS",
    faqLead: "GlideWeather’ın bugünkü davranışına uyan yanıtlar.",
    faq: faq([
      ["Yamaç paraşütünde uçuş penceresi nedir?", "0–100 puan, mevcut durumun süresi ve no-go olmayan en fazla dört gündüz saati."],
      ["Uçmadan önce havaya nasıl bakarım?", "Bölgeyi ara veya bir destinasyon aç, rüzgar, hamle, görüş ve gerekçeleri oku, sonra tam tahmini."],
      ["GlideWeather hangi rüzgarı kullanır?", "10 m rüzgar, hamle ve fark için temkinli eşikler. Brifing filtreleridir, evrensel yasal sınırlar değil."],
      ["Güvenli olup olmadığını söyler mi?", "Hayır. Kalkışa sen karar verirsin; yerel bilgi ve geçerli kurallarla."],
      ["Farklı kalkışlara bakabilir miyim?", "Evet. Dünyada ara, pini taşı, GPS veya bağlantıları kullan. ?site= uygulama durumudur ve dizine eklenmez."],
      ["Tahmin ne kadar doğru?", "Meteoblue veya Open-Meteo’ya bağlıdır. Yanıtlar kısa süre önbellekte kalır. Meteoblue öngörülebilirliği %30’un altındaysa not çıkar."],
      ["Hangi veriler kullanılır?", "Ayarlıysa Meteoblue, değilse Open-Meteo tahmini; hava kalitesi ve yer araması için Open-Meteo."],
    ]),
    homeTitle: "Tek yerde yamaç paraşütü havası",
    homeA: "GlideWeather hiper yerel tahmini gerekçeli bir puana çevirir: rüzgar, hamle farkı, görüş, yağış ve kararsızlık.",
    homeB: "Rehberler kuralları anlatır. Bölgeler konsolu açar ve bugün uçulur demez.",
    hubTitle: "Popüler yamaç paraşütü bölgeleri",
    hubLead: "Brifing için bir seçki. Listede olmak bugün uçulur demek değildir.",
    hubUse: "Her sayfa bağlam, sezon ve referans koordinatları anlatır. «Tahmini aç» konsolu yükler.",
    h: {
      problem: "Hangi sorunu çözer",
      who: "Kim için",
      different: "Farkı ne",
      limits: "Ne iddia etmez",
      flow: "Akış",
      output: "Ne görürsün",
      data: "Kaynaklar",
      wind: "10 m rüzgar ve hamle",
      visibility: "Görüş",
      precip: "Yağış",
      instability: "Kararsızlık ve bulut",
      air: "Hava kalitesi ve UV",
      travel: "Yola çıkmadan",
      day: "Uçuş günü",
      monitor: "Değişirse",
      score: "Puan",
      until: "Şu saate kadar uygun…",
      ranked: "Sıralanmış gündüz saatleri",
      chart: "Sonraki altı saat",
      use: "Liste nasıl kullanılır",
    },
  });
}

function packHr(): GuideCopyBundle {
  return fromPack({
    ...itPack,
    disclaimer: "Pomoć pri odluci, ne odobrenje leta. Provjeri stvarni vjetar na startu, rotor, konvekciju, pravila područja i vlastite granice.",
    updated: "Zadnje ažuriranje",
    aboutTitle: "O GlideWeatheru",
    aboutLead: "Hiperlokalna konzola vremena za parajedrilicu: vjetar, udari, vidljivost i nestabilnost prije odlaska na start.",
    problem: "Obične aplikacije pokazuju brojeve, rijetko prema opreznim granicama parajedrilice. GlideWeather svugdje primjenjuje ista pravila.",
    who: "Za pilote koji već poznaju teren, zračni prostor i vlastite granice. Ne zamjenjuje briefing ni školu.",
    different: "Meteoblue ako je poslužitelj postavljen, inače Open-Meteo. Iz toga su ocjena, prsten i razlozi.",
    limits: "Biti na popisu ne znači da se danas leti. GlideWeather ne odobrava start.",
    howTitle: "Kako radi GlideWeather",
    howLead: "Od koordinata do ocjene: mjesto, prognoza, signali, prozor letenja.",
    flow: "Mjesto biraš pretragom, kartom, GPS-om ili spremljenom postavkom. Svaki sat se ocjenjuje istim pravilima vjetra, udara, raspona, oborine, vidljivosti i CAPE-a.",
    output: "Ploča pokazuje vjetar, udare, procijenjenu bazu, vidljivost i šest sati. Ladica dodaje dane, CAPE i do četiri dnevna sata koji nisu no-go.",
    data: "Prognoza: Meteoblue s ključem, inače Open-Meteo. Kvaliteta zraka i geokodiranje: Open-Meteo.",
    weatherTitle: "Vrijeme za parajedrilicu u GlideWeatheru",
    weatherLead: "Samo vrijednosti koje GlideWeather stvarno učita i kako ulaze u ocjenu.",
    wind: "Preslab ili prejak vjetar, nedostajući udari, visoki udari i velik raspon signali su rizika.",
    visibility: "Ispod otprilike 10 km oprez; ispod 5 km je no-go u automatskim pravilima.",
    precip: "Količina i vjerojatnost kiše utječu na ocjenu.",
    instability: "CAPE iznad pragova znači oprez ili no-go. Baza na ploči procjena je iz temperature i vlage.",
    air: "Američki AQI i visok UV mogu oduzeti bodove. To su popratni signali.",
    whenTitle: "Kad koristiti GlideWeather",
    whenLead: "Praktični trenuci: zeleni prsten nije odobrenje starta.",
    travel: "Usporedi vjetar i udare među područjima. Stranica je kontekst; konzola je prognoza u referentnoj točki.",
    day: "Pročitaj ocjenu i razloge prije slaganja i opet ako se promijene oblaci ili vjetar.",
    monitor: "Odgovor ostaje u predmemoriji oko 20 minuta.",
    windowTitle: "Što je prozor letenja?",
    windowLead: "U GlideWeatheru to su tri stvari: ocjena, vremenski redak i poredani dnevni sati.",
    score: "Svaki uzorak kreće od 100. Tvrde granice nameću no-go. Oprez ili ocjena ispod praga je granična.",
    until: "Aplikacija prolazi sate dana i vidi koliko traje isto stanje.",
    ranked: "Do četiri sata koji nisu no-go. Zasebni sati, ne blok.",
    chart: "Boje označavaju dobre sate čiji vjetar ne raste više od oko 3 km/h u odnosu na prethodni sat.",
    faqTitle: "Česta pitanja o vremenu za parajedrilicu",
    faqLead: "Odgovori usklađeni s time kako se GlideWeather danas ponaša.",
    faq: faq([
      ["Što je prozor letenja u parajedrilici?", "Ocjena 0–100, koliko traje trenutačno stanje i do četiri dnevna sata koji nisu no-go."],
      ["Kako provjeriti vrijeme prije leta?", "Potraži područje ili otvori odredište, pročitaj vjetar, udare, vidljivost i razloge, zatim cijelu prognozu."],
      ["Koji vjetar GlideWeather koristi?", "Oprezni pragovi vjetra na 10 m, udara i raspona. To su filtri za briefing, ne opći zakonski limiti."],
      ["Kaže li je li sigurno?", "Ne. O startu odlučuješ ti, uz znanje terena i važeća pravila."],
      ["Mogu li usporediti različite startove?", "Da. Traži po svijetu, pomakni pribadaču, koristi GPS ili poveznice. ?site= je stanje aplikacije i ne indeksira se."],
      ["Koliko je prognoza točna?", "Ovisi o Meteoblueu ili Open-Meteu. Odgovori se kratko pohranjuju. Ispod 30 % predvidljivosti Meteobluea pojavi se napomena."],
      ["Koji se podaci koriste?", "Meteoblue ako je postavljen, inače prognoza Open-Metea; Open-Meteo za kvalitetu zraka i traženje mjesta."],
    ]),
    homeTitle: "Vrijeme za parajedrilicu na jednom mjestu",
    homeA: "GlideWeather od hiperlokalne prognoze radi ocjenu s razlozima: vjetar, raspon udara, vidljivost, oborina i nestabilnost.",
    homeB: "Vodiči objašnjavaju pravila. Odredišta otvaraju konzolu i ne tvrde da se danas leti.",
    hubTitle: "Popularna odredišta za parajedrilicu",
    hubLead: "Izbor za briefing. Unos ne znači da se danas leti.",
    hubUse: "Svaka stranica opisuje kontekst, sezonu i referentne koordinate. «Otvori prognozu» učitava konzolu.",
    h: {
      problem: "Koji problem rješava",
      who: "Za koga",
      different: "Što je drugačije",
      limits: "Što ne tvrdi",
      flow: "Tijek",
      output: "Što vidiš",
      data: "Izvori",
      wind: "Vjetar i udari na 10 m",
      visibility: "Vidljivost",
      precip: "Oborina",
      instability: "Nestabilnost i oblaci",
      air: "Kvaliteta zraka i UV",
      travel: "Prije puta",
      day: "Na dan leta",
      monitor: "Ako se promijeni",
      score: "Ocjena",
      until: "Povoljno do…",
      ranked: "Poredani dnevni sati",
      chart: "Sljedećih šest sati",
      use: "Kako koristiti popis",
    },
  });
}

function packSr(): GuideCopyBundle {
  return fromPack({
    ...itPack,
    disclaimer: "Pomoć pri odluci, ne odobrenje leta. Proveri stvarni vetar na startu, rotor, konvekciju, pravila područja i sopstvene granice.",
    updated: "Poslednje ažuriranje",
    aboutTitle: "O GlideWeather-u",
    aboutLead: "Hiperlokalna konzola vremena za paraglajding: vetar, udari, vidljivost i nestabilnost pre odlaska na start.",
    problem: "Obične aplikacije pokazuju brojeve, retko prema opreznim granicama paraglajdinga. GlideWeather svuda primenjuje ista pravila.",
    who: "Za pilote koji već poznaju teren, vazdušni prostor i sopstvene granice. Ne zamenjuje brifing ni školu.",
    different: "Meteoblue ako je server podešen, inače Open-Meteo. Iz toga su ocena, prsten i razlozi.",
    limits: "Biti na spisku ne znači da se danas leti. GlideWeather ne odobrava start.",
    howTitle: "Kako radi GlideWeather",
    howLead: "Od koordinata do ocene: mesto, prognoza, signali, prozor letenja.",
    flow: "Mesto biraš pretragom, kartom, GPS-om ili sačuvanom postavkom. Svaki sat se ocenjuje istim pravilima vetra, udara, raspona, padavina, vidljivosti i CAPE-a.",
    output: "Ploča pokazuje vetar, udare, procenjenu bazu, vidljivost i šest sati. Fioka dodaje dane, CAPE i do četiri dnevna sata koji nisu no-go.",
    data: "Prognoza: Meteoblue sa ključem, inače Open-Meteo. Kvalitet vazduha i geokodiranje: Open-Meteo.",
    weatherTitle: "Vreme za paraglajding u GlideWeather-u",
    weatherLead: "Samo vrednosti koje GlideWeather stvarno učita i kako ulaze u ocenu.",
    wind: "Preslab ili prejak vetar, nedostajući udari, visoki udari i veliki raspon signali su rizika.",
    visibility: "Ispod otprilike 10 km oprez; ispod 5 km je no-go u automatskim pravilima.",
    precip: "Količina i verovatnoća kiše utiču na ocenu.",
    instability: "CAPE iznad pragova znači oprez ili no-go. Baza na ploči je procena iz temperature i vlage.",
    air: "Američki AQI i visok UV mogu oduzeti poene. To su prateći signali.",
    whenTitle: "Kada koristiti GlideWeather",
    whenLead: "Praktični trenuci: zeleni prsten nije odobrenje starta.",
    travel: "Uporedi vetar i udare među područjima. Stranica je kontekst; konzola je prognoza u referentnoj tački.",
    day: "Pročitaj ocenu i razloge pre slaganja i opet ako se promene oblaci ili vetar.",
    monitor: "Odgovor ostaje u kešu oko 20 minuta.",
    windowTitle: "Šta je prozor letenja?",
    windowLead: "U GlideWeather-u to su tri stvari: ocena, vremenski red i poređani dnevni sati.",
    score: "Svaki uzorak kreće od 100. Tvrde granice nameću no-go. Oprez ili ocena ispod praga je granična.",
    until: "Aplikacija prolazi sate dana i vidi koliko traje isto stanje.",
    ranked: "Do četiri sata koji nisu no-go. Zasebni sati, ne blok.",
    chart: "Boje označavaju dobre sate čiji vetar ne raste više od oko 3 km/h u odnosu na prethodni sat.",
    faqTitle: "Česta pitanja o vremenu za paraglajding",
    faqLead: "Odgovori usklađeni sa tim kako se GlideWeather danas ponaša.",
    faq: faq([
      ["Šta je prozor letenja u paraglajdingu?", "Ocena 0–100, koliko traje trenutno stanje i do četiri dnevna sata koji nisu no-go."],
      ["Kako proveriti vreme pre leta?", "Potraži područje ili otvori destinaciju, pročitaj vetar, udare, vidljivost i razloge, zatim celu prognozu."],
      ["Koji vetar GlideWeather koristi?", "Oprezni pragovi vetra na 10 m, udara i raspona. To su filteri za brifing, ne opšti zakonski limiti."],
      ["Kaže li da li je bezbedno?", "Ne. O startu odlučuješ ti, uz znanje terena i važeća pravila."],
      ["Mogu li da uporedim različite startove?", "Da. Traži po svetu, pomeri čiocu, koristi GPS ili veze. ?site= je stanje aplikacije i ne indeksira se."],
      ["Koliko je prognoza tačna?", "Zavisi od Meteoblue ili Open-Meteo. Odgovori se kratko čuvaju. Ispod 30 % predvidljivosti Meteoblue pojavljuje se napomena."],
      ["Koji podaci se koriste?", "Meteoblue ako je podešen, inače prognoza Open-Meteo; Open-Meteo za kvalitet vazduha i traženje mesta."],
    ]),
    homeTitle: "Vreme za paraglajding na jednom mestu",
    homeA: "GlideWeather od hiperlokalne prognoze pravi ocenu sa razlozima: vetar, raspon udara, vidljivost, padavine i nestabilnost.",
    homeB: "Vodiči objašnjavaju pravila. Destinacije otvaraju konzolu i ne tvrde da se danas leti.",
    hubTitle: "Popularne destinacije za paraglajding",
    hubLead: "Izbor za brifing. Unos ne znači da se danas leti.",
    hubUse: "Svaka stranica opisuje kontekst, sezonu i referentne koordinate. «Otvori prognozu» učitava konzolu.",
    h: {
      problem: "Koji problem rešava",
      who: "Za koga",
      different: "Šta je drugačije",
      limits: "Šta ne tvrdi",
      flow: "Tok",
      output: "Šta vidiš",
      data: "Izvori",
      wind: "Vetar i udari na 10 m",
      visibility: "Vidljivost",
      precip: "Padavine",
      instability: "Nestabilnost i oblaci",
      air: "Kvalitet vazduha i UV",
      travel: "Pre puta",
      day: "Na dan leta",
      monitor: "Ako se promeni",
      score: "Ocena",
      until: "Povoljno do…",
      ranked: "Poređani dnevni sati",
      chart: "Sledećih šest sati",
      use: "Kako koristiti spisak",
    },
  });
}

function packSq(): GuideCopyBundle {
  return fromPack({
    ...itPack,
    disclaimer: "Ndihmë për vendim, jo autorizim fluturimi. Konfirmo erën e vërtetë në nisje, rotorin, konveksionin, rregullat e zonës dhe kufijtë e tu.",
    updated: "Përditësuar së fundmi",
    aboutTitle: "Rreth GlideWeather",
    aboutLead: "Konsolë moti hiperlokale për paragliding: erë, goditje, dukshmëri dhe paqëndrueshmëri para se të shkosh në nisje.",
    problem: "Aplikacionet e përgjithshme tregojnë numra, rrallë kundrejt kufijve të kujdesshëm të paraglidingut. GlideWeather përdor të njëjtat rregulla kudo.",
    who: "Për pilotë që e njohin tashmë terrenin, hapësirën ajrore dhe kufijtë e tyre. Nuk zëvendëson briefingun as shkollën.",
    different: "Meteoblue nëse serveri është konfiguruar, përndryshe Open-Meteo. Prej tyre dalin pika, unaza dhe arsyet.",
    limits: "Të jesh në listë nuk do të thotë që sot fluturohet. GlideWeather nuk autorizon nisjen.",
    howTitle: "Si funksionon GlideWeather",
    howLead: "Nga koordinatat te vendimi: vendi, parashikimi, sinjalet, dritarja e fluturimit.",
    flow: "Vendi zgjidhet me kërkim, hartë, GPS ose preferencë të ruajtur. Çdo orë vlerësohet me të njëjtat rregulla të erës, goditjeve, hapësirës, reshjeve, dukshmërisë dhe CAPE.",
    output: "Paneli tregon erën, goditjet, bazën e vlerësuar, dukshmërinë dhe gjashtë orë. Sirtari shton ditët, CAPE dhe deri në katër orë drite që nuk janë no-go.",
    data: "Parashikim: Meteoblue me çelës, përndryshe Open-Meteo. Cilësia e ajrit dhe gjeokodimi: Open-Meteo.",
    weatherTitle: "Moti për paragliding në GlideWeather",
    weatherLead: "Vetëm vlerat që GlideWeather ngarkon vërtet dhe si hyjnë në vendim.",
    wind: "Erë shumë e dobët ose e fortë, goditje që mungojnë, goditje të larta dhe hapësirë e madhe janë sinjale rreziku.",
    visibility: "Nën rreth 10 km kujdes; nën 5 km është no-go në rregullat automatike.",
    precip: "Sasia dhe probabiliteti i shiut ndikojnë pikën.",
    instability: "CAPE mbi pragje sjell kujdes ose no-go. Baza në panel vlerësohet nga temperatura dhe lagështia.",
    air: "AQI amerikan dhe UV e lartë mund të heqin pikë. Janë sinjale mbështetëse.",
    whenTitle: "Kur të përdorësh GlideWeather",
    whenLead: "Çaste praktike: një unazë e gjelbër nuk është leje nisjeje.",
    travel: "Krahaso erën dhe goditjet mes zonave. Faqja është kontekst; konsola është parashikimi në pikën e referencës.",
    day: "Lexo pikën dhe arsyet para se të montosh dhe përsëri nëse ndryshojnë retë ose era.",
    monitor: "Përgjigjja qëndron në cache rreth 20 minuta.",
    windowTitle: "Çfarë është dritarja e fluturimit?",
    windowLead: "Në GlideWeather janë tri gjëra: pika, rreshti i kohës dhe orët e dritës të renditura.",
    score: "Çdo kampion fillon nga 100. Kufijtë e fortë detyrojnë no-go. Kujdesi ose një pikë nën prag është kufitare.",
    until: "Aplikacioni kalon orët e ditës dhe sheh sa zgjat i njëjti gjendje.",
    ranked: "Deri në katër orë që nuk janë no-go. Orë të veçanta, jo bllok.",
    chart: "Ngjyrat shënojnë orë të mira era e të cilave nuk rritet më shumë se rreth 3 km/h nga ora e mëparshme.",
    faqTitle: "Pyetje të shpeshta për motin e paraglidingut",
    faqLead: "Përgjigje në përputhje me sjelljen e sotme të GlideWeather.",
    faq: faq([
      ["Çfarë është dritarja e fluturimit në paragliding?", "Pika 0–100, sa zgjat gjendja aktuale dhe deri në katër orë drite që nuk janë no-go."],
      ["Si e kontrolloj motin para se të fluturoj?", "Kërko zonën ose hap një destinacion, lexo erën, goditjet, dukshmërinë dhe arsyet, pastaj parashikimin e plotë."],
      ["Çfarë ere përdor GlideWeather?", "Pragje të kujdesshme të erës në 10 m, goditjeve dhe hapësirës. Janë filtra briefingu, jo kufij të përgjithshëm ligjorë."],
      ["Më thotë nëse është e sigurt?", "Jo. Nisjen e vendos ti, me njohje lokale dhe rregullat në fuqi."],
      ["A mund të krahasoj nisje të ndryshme?", "Po. Kërko në botë, lëviz pinin, përdor GPS ose lidhjet. ?site= është gjendje e aplikacionit dhe nuk indeksohet."],
      ["Sa i saktë është parashikimi?", "Varet nga Meteoblue ose Open-Meteo. Përgjigjet ruhen shkurt. Nën 30 % parashikueshmëri të Meteoblue shfaqet një shënim."],
      ["Çfarë të dhënash përdoren?", "Meteoblue nëse është konfiguruar, përndryshe parashikimi Open-Meteo; Open-Meteo për cilësinë e ajrit dhe kërkimin e vendeve."],
    ]),
    homeTitle: "Moti për paragliding në një vend",
    homeA: "GlideWeather e kthen parashikimin hiperlokal në një pikë me arsye: erë, hapësirë goditjesh, dukshmëri, reshje dhe paqëndrueshmëri.",
    homeB: "Udhëzuesit shpjegojnë rregullat. Destinacionet hapin konsolën dhe nuk thonë që sot fluturohet.",
    hubTitle: "Destinacione të njohura paragliding",
    hubLead: "Një përzgjedhje për briefing. Të jesh në listë nuk do të thotë që sot fluturohet.",
    hubUse: "Çdo faqe përshkruan kontekstin, sezonin dhe koordinatat e referencës. «Hap parashikimin» ngarkon konsolën.",
    h: {
      problem: "Çfarë problemi zgjidh",
      who: "Për kë",
      different: "Çfarë është ndryshe",
      limits: "Çfarë nuk pretendon",
      flow: "Rrjedha",
      output: "Çfarë sheh",
      data: "Burimet",
      wind: "Era dhe goditjet në 10 m",
      visibility: "Dukshmëria",
      precip: "Reshjet",
      instability: "Paqëndrueshmëria dhe retë",
      air: "Cilësia e ajrit dhe UV",
      travel: "Para rrugës",
      day: "Në ditën e fluturimit",
      monitor: "Nëse ndryshon",
      score: "Pika",
      until: "E favorshme deri…",
      ranked: "Orët e dritës të renditura",
      chart: "Gjashtë orët e ardhshme",
      use: "Si përdoret lista",
    },
  });
}
